/*
###############################################################
#  Generated by:      Cadence Innovus 20.15-s105_1
#  OS:                Linux x86_64(Host ID ee28)
#  Generated on:      Thu Dec  5 04:24:39 2024
#  Design:            CHIP
#  Command:           saveNetlist CHIP.v
###############################################################
*/
/////////////////////////////////////////////////////////////
// Created by: Synopsys DC Ultra(TM) in wire load mode
// Version   : T-2022.03
// Date      : Thu Dec  5 00:16:32 2024
/////////////////////////////////////////////////////////////
module TETRIS (
	rst_n, 
	clk, 
	in_valid, 
	tetrominoes, 
	position, 
	tetris_valid, 
	score_valid, 
	fail, 
	score, 
	tetris);
   input rst_n;
   input clk;
   input in_valid;
   input [2:0] tetrominoes;
   input [2:0] position;
   output tetris_valid;
   output score_valid;
   output fail;
   output [3:0] score;
   output [71:0] tetris;

   // Internal wires
   wire CTS_10;
   wire CTS_9;
   wire CTS_8;
   wire CTS_7;
   wire CTS_4;
   wire CTS_6;
   wire CTS_5;
   wire CTS_1;
   wire CTS_3;
   wire CTS_2;
   wire next_state_0_;
   wire bottom_2__0_;
   wire bottom_1__0_;
   wire bottom_0__0_;
   wire N700;
   wire N701;
   wire N702;
   wire N703;
   wire N704;
   wire N705;
   wire N706;
   wire N707;
   wire N708;
   wire N709;
   wire N710;
   wire N711;
   wire N712;
   wire N713;
   wire N714;
   wire N715;
   wire N716;
   wire N717;
   wire N718;
   wire N719;
   wire N720;
   wire N721;
   wire N722;
   wire N723;
   wire map_f_12__5_;
   wire map_f_12__4_;
   wire map_f_12__3_;
   wire map_f_12__2_;
   wire map_f_12__1_;
   wire map_f_12__0_;
   wire map_f_11__5_;
   wire map_f_11__4_;
   wire map_f_11__3_;
   wire map_f_11__2_;
   wire map_f_11__1_;
   wire map_f_11__0_;
   wire map_f_10__5_;
   wire map_f_10__4_;
   wire map_f_10__3_;
   wire map_f_10__2_;
   wire map_f_10__1_;
   wire map_f_10__0_;
   wire map_f_9__5_;
   wire map_f_9__4_;
   wire map_f_9__3_;
   wire map_f_9__2_;
   wire map_f_9__1_;
   wire map_f_9__0_;
   wire map_f_8__5_;
   wire map_f_8__4_;
   wire map_f_8__3_;
   wire map_f_8__2_;
   wire map_f_8__1_;
   wire map_f_8__0_;
   wire map_f_7__5_;
   wire map_f_7__4_;
   wire map_f_7__3_;
   wire map_f_7__2_;
   wire map_f_7__1_;
   wire map_f_7__0_;
   wire map_f_6__5_;
   wire map_f_6__4_;
   wire map_f_6__3_;
   wire map_f_6__2_;
   wire map_f_6__1_;
   wire map_f_6__0_;
   wire map_f_5__5_;
   wire map_f_5__4_;
   wire map_f_5__3_;
   wire map_f_5__2_;
   wire map_f_5__1_;
   wire map_f_5__0_;
   wire map_f_4__5_;
   wire map_f_4__4_;
   wire map_f_4__3_;
   wire map_f_4__2_;
   wire map_f_4__1_;
   wire map_f_4__0_;
   wire map_f_3__5_;
   wire map_f_3__4_;
   wire map_f_3__3_;
   wire map_f_3__2_;
   wire map_f_3__1_;
   wire map_f_3__0_;
   wire map_f_2__5_;
   wire map_f_2__4_;
   wire map_f_2__3_;
   wire map_f_2__2_;
   wire map_f_2__1_;
   wire map_f_2__0_;
   wire map_f_1__5_;
   wire map_f_1__4_;
   wire map_f_1__3_;
   wire map_f_1__2_;
   wire map_f_1__1_;
   wire map_f_1__0_;
   wire map_f_0__5_;
   wire map_f_0__4_;
   wire map_f_0__3_;
   wire map_f_0__2_;
   wire map_f_0__1_;
   wire map_f_0__0_;
   wire N964;
   wire n641;
   wire n642;
   wire n643;
   wire n644;
   wire n645;
   wire n646;
   wire n647;
   wire n648;
   wire n649;
   wire n650;
   wire n651;
   wire n652;
   wire n653;
   wire n654;
   wire n655;
   wire n656;
   wire n657;
   wire n658;
   wire n659;
   wire n660;
   wire n661;
   wire n662;
   wire n663;
   wire n664;
   wire n665;
   wire n666;
   wire n667;
   wire n668;
   wire n669;
   wire n670;
   wire n671;
   wire n672;
   wire n673;
   wire n674;
   wire n675;
   wire n676;
   wire n677;
   wire n678;
   wire n679;
   wire n680;
   wire n681;
   wire n682;
   wire n683;
   wire n684;
   wire n685;
   wire n686;
   wire n687;
   wire n688;
   wire n689;
   wire n690;
   wire n691;
   wire n692;
   wire n693;
   wire n694;
   wire n695;
   wire n696;
   wire n697;
   wire n698;
   wire n699;
   wire n7000;
   wire n7010;
   wire n7020;
   wire n7030;
   wire n7040;
   wire n7050;
   wire n7060;
   wire n7070;
   wire n7080;
   wire n7090;
   wire n7100;
   wire n7110;
   wire n7120;
   wire n7130;
   wire n7140;
   wire n7150;
   wire n7160;
   wire n7170;
   wire n7180;
   wire n7190;
   wire n7200;
   wire n7210;
   wire n7220;
   wire n7230;
   wire n724;
   wire n725;
   wire n726;
   wire n727;
   wire n728;
   wire n729;
   wire n730;
   wire n731;
   wire n732;
   wire n733;
   wire n734;
   wire n735;
   wire n736;
   wire n737;
   wire n738;
   wire n739;
   wire n740;
   wire n741;
   wire n742;
   wire n743;
   wire n744;
   wire n745;
   wire n746;
   wire n747;
   wire n748;
   wire n749;
   wire n750;
   wire n751;
   wire n752;
   wire n753;
   wire intadd_2_A_1_;
   wire intadd_2_A_0_;
   wire intadd_3_A_2_;
   wire intadd_3_A_1_;
   wire intadd_3_B_2_;
   wire intadd_3_B_1_;
   wire intadd_3_B_0_;
   wire intadd_3_CI;
   wire intadd_3_SUM_0_;
   wire intadd_3_n3;
   wire intadd_3_n2;
   wire intadd_3_n1;
   wire n763;
   wire n764;
   wire n765;
   wire n766;
   wire n767;
   wire n768;
   wire n769;
   wire n770;
   wire n771;
   wire n772;
   wire n773;
   wire n774;
   wire n775;
   wire n776;
   wire n777;
   wire n778;
   wire n779;
   wire n780;
   wire n781;
   wire n782;
   wire n783;
   wire n784;
   wire n785;
   wire n786;
   wire n787;
   wire n788;
   wire n789;
   wire n790;
   wire n791;
   wire n792;
   wire n793;
   wire n794;
   wire n795;
   wire n796;
   wire n797;
   wire n798;
   wire n799;
   wire n800;
   wire n801;
   wire n802;
   wire n803;
   wire n804;
   wire n805;
   wire n806;
   wire n807;
   wire n808;
   wire n809;
   wire n810;
   wire n811;
   wire n812;
   wire n813;
   wire n814;
   wire n815;
   wire n816;
   wire n817;
   wire n818;
   wire n819;
   wire n820;
   wire n821;
   wire n822;
   wire n823;
   wire n824;
   wire n825;
   wire n826;
   wire n827;
   wire n828;
   wire n829;
   wire n830;
   wire n831;
   wire n832;
   wire n833;
   wire n834;
   wire n835;
   wire n836;
   wire n837;
   wire n838;
   wire n839;
   wire n840;
   wire n841;
   wire n842;
   wire n843;
   wire n844;
   wire n845;
   wire n846;
   wire n847;
   wire n848;
   wire n849;
   wire n850;
   wire n851;
   wire n852;
   wire n853;
   wire n854;
   wire n855;
   wire n856;
   wire n857;
   wire n858;
   wire n859;
   wire n860;
   wire n861;
   wire n862;
   wire n863;
   wire n864;
   wire n865;
   wire n866;
   wire n867;
   wire n868;
   wire n869;
   wire n870;
   wire n871;
   wire n872;
   wire n873;
   wire n874;
   wire n875;
   wire n876;
   wire n877;
   wire n878;
   wire n879;
   wire n880;
   wire n881;
   wire n882;
   wire n883;
   wire n884;
   wire n885;
   wire n886;
   wire n887;
   wire n888;
   wire n889;
   wire n890;
   wire n891;
   wire n892;
   wire n893;
   wire n894;
   wire n895;
   wire n896;
   wire n897;
   wire n898;
   wire n899;
   wire n900;
   wire n901;
   wire n902;
   wire n903;
   wire n904;
   wire n905;
   wire n906;
   wire n907;
   wire n908;
   wire n909;
   wire n910;
   wire n911;
   wire n912;
   wire n913;
   wire n914;
   wire n915;
   wire n916;
   wire n917;
   wire n918;
   wire n919;
   wire n920;
   wire n921;
   wire n922;
   wire n923;
   wire n924;
   wire n925;
   wire n926;
   wire n927;
   wire n928;
   wire n929;
   wire n930;
   wire n931;
   wire n932;
   wire n933;
   wire n934;
   wire n935;
   wire n936;
   wire n937;
   wire n938;
   wire n939;
   wire n940;
   wire n941;
   wire n942;
   wire n943;
   wire n944;
   wire n945;
   wire n946;
   wire n947;
   wire n948;
   wire n949;
   wire n950;
   wire n951;
   wire n952;
   wire n953;
   wire n954;
   wire n955;
   wire n956;
   wire n957;
   wire n958;
   wire n959;
   wire n960;
   wire n961;
   wire n962;
   wire n963;
   wire n9640;
   wire n965;
   wire n966;
   wire n967;
   wire n968;
   wire n969;
   wire n970;
   wire n971;
   wire n972;
   wire n973;
   wire n974;
   wire n975;
   wire n976;
   wire n977;
   wire n978;
   wire n979;
   wire n980;
   wire n981;
   wire n982;
   wire n983;
   wire n984;
   wire n985;
   wire n986;
   wire n987;
   wire n988;
   wire n989;
   wire n990;
   wire n991;
   wire n992;
   wire n993;
   wire n994;
   wire n995;
   wire n996;
   wire n997;
   wire n998;
   wire n999;
   wire n1000;
   wire n1001;
   wire n1002;
   wire n1003;
   wire n1004;
   wire n1005;
   wire n1006;
   wire n1007;
   wire n1008;
   wire n1009;
   wire n1010;
   wire n1011;
   wire n1012;
   wire n1013;
   wire n1014;
   wire n1015;
   wire n1016;
   wire n1017;
   wire n1018;
   wire n1019;
   wire n1020;
   wire n1021;
   wire n1022;
   wire n1023;
   wire n1024;
   wire n1025;
   wire n1026;
   wire n1027;
   wire n1028;
   wire n1029;
   wire n1030;
   wire n1031;
   wire n1032;
   wire n1033;
   wire n1034;
   wire n1035;
   wire n1036;
   wire n1037;
   wire n1038;
   wire n1039;
   wire n1040;
   wire n1041;
   wire n1042;
   wire n1043;
   wire n1044;
   wire n1045;
   wire n1046;
   wire n1047;
   wire n1048;
   wire n1049;
   wire n1050;
   wire n1051;
   wire n1052;
   wire n1053;
   wire n1054;
   wire n1055;
   wire n1056;
   wire n1057;
   wire n1058;
   wire n1059;
   wire n1060;
   wire n1061;
   wire n1062;
   wire n1063;
   wire n1064;
   wire n1065;
   wire n1066;
   wire n1067;
   wire n1068;
   wire n1069;
   wire n1070;
   wire n1071;
   wire n1072;
   wire n1073;
   wire n1074;
   wire n1075;
   wire n1076;
   wire n1077;
   wire n1078;
   wire n1079;
   wire n1080;
   wire n1081;
   wire n1082;
   wire n1083;
   wire n1084;
   wire n1085;
   wire n1086;
   wire n1087;
   wire n1088;
   wire n1089;
   wire n1090;
   wire n1091;
   wire n1092;
   wire n1093;
   wire n1094;
   wire n1095;
   wire n1096;
   wire n1097;
   wire n1098;
   wire n1099;
   wire n1100;
   wire n1101;
   wire n1102;
   wire n1103;
   wire n1104;
   wire n1105;
   wire n1106;
   wire n1107;
   wire n1108;
   wire n1109;
   wire n1110;
   wire n1111;
   wire n1112;
   wire n1113;
   wire n1114;
   wire n1115;
   wire n1116;
   wire n1117;
   wire n1118;
   wire n1119;
   wire n1120;
   wire n1121;
   wire n1122;
   wire n1123;
   wire n1124;
   wire n1125;
   wire n1126;
   wire n1127;
   wire n1128;
   wire n1129;
   wire n1130;
   wire n1131;
   wire n1132;
   wire n1133;
   wire n1134;
   wire n1135;
   wire n1136;
   wire n1137;
   wire n1138;
   wire n1139;
   wire n1140;
   wire n1141;
   wire n1142;
   wire n1143;
   wire n1144;
   wire n1145;
   wire n1146;
   wire n1147;
   wire n1148;
   wire n1149;
   wire n1150;
   wire n1151;
   wire n1152;
   wire n1153;
   wire n1154;
   wire n1155;
   wire n1156;
   wire n1157;
   wire n1158;
   wire n1159;
   wire n1160;
   wire n1161;
   wire n1162;
   wire n1163;
   wire n1164;
   wire n1165;
   wire n1166;
   wire n1167;
   wire n1168;
   wire n1169;
   wire n1170;
   wire n1171;
   wire n1172;
   wire n1173;
   wire n1174;
   wire n1175;
   wire n1176;
   wire n1177;
   wire n1178;
   wire n1179;
   wire n1180;
   wire n1181;
   wire n1182;
   wire n1183;
   wire n1184;
   wire n1185;
   wire n1186;
   wire n1187;
   wire n1188;
   wire n1189;
   wire n1190;
   wire n1191;
   wire n1192;
   wire n1193;
   wire n1194;
   wire n1195;
   wire n1196;
   wire n1197;
   wire n1198;
   wire n1199;
   wire n1200;
   wire n1201;
   wire n1202;
   wire n1203;
   wire n1204;
   wire n1205;
   wire n1206;
   wire n1207;
   wire n1208;
   wire n1209;
   wire n1210;
   wire n1211;
   wire n1212;
   wire n1213;
   wire n1214;
   wire n1215;
   wire n1216;
   wire n1217;
   wire n1218;
   wire n1219;
   wire n1220;
   wire n1221;
   wire n1222;
   wire n1223;
   wire n1224;
   wire n1225;
   wire n1226;
   wire n1227;
   wire n1228;
   wire n1229;
   wire n1230;
   wire n1231;
   wire n1232;
   wire n1233;
   wire n1234;
   wire n1235;
   wire n1236;
   wire n1237;
   wire n1238;
   wire n1239;
   wire n1240;
   wire n1241;
   wire n1242;
   wire n1243;
   wire n1244;
   wire n1245;
   wire n1246;
   wire n1247;
   wire n1248;
   wire n1249;
   wire n1250;
   wire n1251;
   wire n1252;
   wire n1253;
   wire n1254;
   wire n1255;
   wire n1256;
   wire n1257;
   wire n1258;
   wire n1259;
   wire n1260;
   wire n1261;
   wire n1262;
   wire n1263;
   wire n1264;
   wire n1265;
   wire n1266;
   wire n1267;
   wire n1268;
   wire n1269;
   wire n1270;
   wire n1271;
   wire n1272;
   wire n1273;
   wire n1274;
   wire n1275;
   wire n1276;
   wire n1277;
   wire n1278;
   wire n1279;
   wire n1280;
   wire n1281;
   wire n1282;
   wire n1283;
   wire n1284;
   wire n1285;
   wire n1286;
   wire n1287;
   wire n1288;
   wire n1289;
   wire n1290;
   wire n1291;
   wire n1292;
   wire n1293;
   wire n1294;
   wire n1295;
   wire n1296;
   wire n1297;
   wire n1298;
   wire n1299;
   wire n1300;
   wire n1301;
   wire n1302;
   wire n1303;
   wire n1304;
   wire n1305;
   wire n1306;
   wire n1307;
   wire n1308;
   wire n1309;
   wire n1310;
   wire n1311;
   wire n1312;
   wire n1313;
   wire n1314;
   wire n1315;
   wire n1316;
   wire n1317;
   wire n1318;
   wire n1319;
   wire n1320;
   wire n1321;
   wire n1322;
   wire n1323;
   wire n1324;
   wire n1325;
   wire n1326;
   wire n1327;
   wire n1328;
   wire n1329;
   wire n1330;
   wire n1331;
   wire n1332;
   wire n1333;
   wire n1334;
   wire n1335;
   wire n1336;
   wire n1337;
   wire n1338;
   wire n1339;
   wire n1340;
   wire n1341;
   wire n1342;
   wire n1343;
   wire n1344;
   wire n1345;
   wire n1346;
   wire n1347;
   wire n1348;
   wire n1349;
   wire n1350;
   wire n1351;
   wire n1352;
   wire n1353;
   wire n1354;
   wire n1355;
   wire n1356;
   wire n1357;
   wire n1358;
   wire n1359;
   wire n1360;
   wire n1361;
   wire n1362;
   wire n1363;
   wire n1364;
   wire n1365;
   wire n1366;
   wire n1367;
   wire n1368;
   wire n1369;
   wire n1370;
   wire n1371;
   wire n1372;
   wire n1373;
   wire n1374;
   wire n1375;
   wire n1376;
   wire n1377;
   wire n1378;
   wire n1379;
   wire n1380;
   wire n1381;
   wire n1382;
   wire n1383;
   wire n1384;
   wire n1385;
   wire n1386;
   wire n1387;
   wire n1388;
   wire n1389;
   wire n1390;
   wire n1391;
   wire n1392;
   wire n1393;
   wire n1394;
   wire n1395;
   wire n1396;
   wire n1397;
   wire n1398;
   wire n1399;
   wire n1400;
   wire n1401;
   wire n1402;
   wire n1403;
   wire n1404;
   wire n1405;
   wire n1406;
   wire n1407;
   wire n1408;
   wire n1409;
   wire n1410;
   wire n1411;
   wire n1412;
   wire n1413;
   wire n1414;
   wire n1415;
   wire n1416;
   wire n1417;
   wire n1418;
   wire n1419;
   wire n1420;
   wire n1421;
   wire n1422;
   wire n1423;
   wire n1424;
   wire n1425;
   wire n1426;
   wire n1427;
   wire n1428;
   wire n1429;
   wire n1430;
   wire n1431;
   wire n1432;
   wire n1433;
   wire n1434;
   wire n1435;
   wire n1436;
   wire n1437;
   wire n1438;
   wire n1439;
   wire n1440;
   wire n1441;
   wire n1442;
   wire n1443;
   wire n1444;
   wire n1445;
   wire n1446;
   wire n1447;
   wire n1448;
   wire n1449;
   wire n1450;
   wire n1451;
   wire n1452;
   wire n1453;
   wire n1454;
   wire n1455;
   wire n1456;
   wire n1457;
   wire n1458;
   wire n1459;
   wire n1460;
   wire n1461;
   wire n1462;
   wire n1463;
   wire n1464;
   wire n1465;
   wire n1466;
   wire n1467;
   wire n1468;
   wire n1469;
   wire n1470;
   wire n1471;
   wire n1472;
   wire n1473;
   wire n1474;
   wire n1475;
   wire n1476;
   wire n1477;
   wire n1478;
   wire n1479;
   wire n1480;
   wire n1481;
   wire n1482;
   wire [2:0] state;
   wire [3:0] cnt_f;
   wire [3:0] cnt;
   wire [10:0] bottom_f;
   wire [2:0] position_f;
   wire [23:0] tetrominoes_map_f;
   wire [2:0] bottom_compare_f;
   wire [23:0] col_top_f;
   wire [23:0] row_f;
   wire [3:0] score_f;
   wire [3:0] score_comb;
   wire [71:0] tetris_comb;
   wire [23:0] col_top;

   INV12CK CTS_ccl_a_inv_00015 (.O(CTS_6),
	.I(CTS_4));
   INV12CK CTS_ccl_a_inv_00011 (.O(CTS_5),
	.I(CTS_4));
   INV8CK CTS_ccl_a_inv_00022 (.O(CTS_4),
	.I(CTS_7));
   INV12CK CTS_ccl_a_inv_00013 (.O(CTS_3),
	.I(CTS_1));
   INV12CK CTS_ccl_a_inv_00009 (.O(CTS_2),
	.I(CTS_1));
   INV8CK CTS_ccl_a_inv_00020 (.O(CTS_1),
	.I(CTS_7));
   INV8CK CTS_ccl_a_inv_00025 (.O(CTS_7),
	.I(CTS_8));
   INV8CK CTS_ccl_a_inv_00029 (.O(CTS_8),
	.I(CTS_9));
   INV8CK CTS_ccl_inv_00031 (.O(CTS_9),
	.I(CTS_10));
   INV8CK CTS_ccl_inv_00034 (.O(CTS_10),
	.I(clk));
   QDFFRBS state_reg_0_ (.Q(state[0]),
	.D(next_state_0_),
	.CK(CTS_5),
	.RB(n1475));
   QDFFRBS state_reg_2_ (.Q(state[2]),
	.D(n1473),
	.CK(CTS_5),
	.RB(n1475));
   QDFFRBS tetrominoes_map_f_reg_3__0_ (.Q(tetrominoes_map_f[18]),
	.D(n753),
	.CK(CTS_5),
	.RB(n1474));
   QDFFRBS tetrominoes_map_f_reg_3__1_ (.Q(tetrominoes_map_f[19]),
	.D(n752),
	.CK(CTS_5),
	.RB(n1476));
   QDFFRBS tetrominoes_map_f_reg_3__2_ (.Q(tetrominoes_map_f[20]),
	.D(n751),
	.CK(CTS_5),
	.RB(n1474));
   QDFFRBS tetrominoes_map_f_reg_3__3_ (.Q(tetrominoes_map_f[21]),
	.D(n750),
	.CK(CTS_5),
	.RB(n1476));
   QDFFRBS tetrominoes_map_f_reg_3__4_ (.Q(tetrominoes_map_f[22]),
	.D(n749),
	.CK(CTS_5),
	.RB(n1474));
   QDFFRBS tetrominoes_map_f_reg_3__5_ (.Q(tetrominoes_map_f[23]),
	.D(n748),
	.CK(CTS_5),
	.RB(n1475));
   QDFFRBS tetrominoes_map_f_reg_2__0_ (.Q(tetrominoes_map_f[12]),
	.D(n747),
	.CK(CTS_5),
	.RB(n1476));
   QDFFRBS tetrominoes_map_f_reg_2__1_ (.Q(tetrominoes_map_f[13]),
	.D(n746),
	.CK(CTS_5),
	.RB(n1474));
   QDFFRBS tetrominoes_map_f_reg_2__2_ (.Q(tetrominoes_map_f[14]),
	.D(n745),
	.CK(CTS_5),
	.RB(n1474));
   QDFFRBS tetrominoes_map_f_reg_2__3_ (.Q(tetrominoes_map_f[15]),
	.D(n744),
	.CK(CTS_5),
	.RB(n1474));
   QDFFRBS tetrominoes_map_f_reg_2__4_ (.Q(tetrominoes_map_f[16]),
	.D(n743),
	.CK(CTS_5),
	.RB(n1474));
   QDFFRBS tetrominoes_map_f_reg_2__5_ (.Q(tetrominoes_map_f[17]),
	.D(n742),
	.CK(CTS_5),
	.RB(n1474));
   QDFFRBS tetrominoes_map_f_reg_1__0_ (.Q(tetrominoes_map_f[6]),
	.D(n741),
	.CK(CTS_5),
	.RB(n1474));
   QDFFRBS tetrominoes_map_f_reg_1__1_ (.Q(tetrominoes_map_f[7]),
	.D(n740),
	.CK(CTS_5),
	.RB(n1474));
   QDFFRBS tetrominoes_map_f_reg_1__2_ (.Q(tetrominoes_map_f[8]),
	.D(n739),
	.CK(CTS_5),
	.RB(n1474));
   QDFFRBS tetrominoes_map_f_reg_1__3_ (.Q(tetrominoes_map_f[9]),
	.D(n738),
	.CK(CTS_5),
	.RB(n1474));
   QDFFRBS tetrominoes_map_f_reg_1__4_ (.Q(tetrominoes_map_f[10]),
	.D(n737),
	.CK(CTS_5),
	.RB(n1474));
   QDFFRBS tetrominoes_map_f_reg_1__5_ (.Q(tetrominoes_map_f[11]),
	.D(n736),
	.CK(CTS_5),
	.RB(n1474));
   QDFFRBS tetrominoes_map_f_reg_0__0_ (.Q(tetrominoes_map_f[0]),
	.D(n735),
	.CK(CTS_5),
	.RB(n1475));
   QDFFRBS tetrominoes_map_f_reg_0__1_ (.Q(tetrominoes_map_f[1]),
	.D(n734),
	.CK(CTS_5),
	.RB(n1475));
   QDFFRBS tetrominoes_map_f_reg_0__2_ (.Q(tetrominoes_map_f[2]),
	.D(n733),
	.CK(CTS_5),
	.RB(n1475));
   QDFFRBS tetrominoes_map_f_reg_0__3_ (.Q(tetrominoes_map_f[3]),
	.D(n732),
	.CK(CTS_5),
	.RB(n1475));
   QDFFRBS tetrominoes_map_f_reg_0__4_ (.Q(tetrominoes_map_f[4]),
	.D(n731),
	.CK(CTS_5),
	.RB(n1475));
   QDFFRBS tetrominoes_map_f_reg_0__5_ (.Q(tetrominoes_map_f[5]),
	.D(n730),
	.CK(CTS_5),
	.RB(n1475));
   QDFFRBS bottom_f_reg_3__3_ (.Q(bottom_f[10]),
	.D(n1465),
	.CK(CTS_5),
	.RB(n1475));
   QDFFRBS bottom_f_reg_3__2_ (.Q(bottom_f[9]),
	.D(n1465),
	.CK(CTS_5),
	.RB(n1475));
   QDFFRBS bottom_f_reg_2__3_ (.Q(bottom_f[8]),
	.D(n1466),
	.CK(CTS_5),
	.RB(n1475));
   QDFFRBS bottom_f_reg_2__2_ (.Q(bottom_f[7]),
	.D(n1466),
	.CK(CTS_5),
	.RB(n1475));
   QDFFRBS bottom_f_reg_2__0_ (.Q(bottom_f[6]),
	.D(bottom_2__0_),
	.CK(CTS_5),
	.RB(n1475));
   QDFFRBS bottom_f_reg_1__3_ (.Q(bottom_f[5]),
	.D(n1467),
	.CK(CTS_5),
	.RB(n1476));
   QDFFRBS bottom_f_reg_1__2_ (.Q(bottom_f[4]),
	.D(n1467),
	.CK(CTS_5),
	.RB(n1476));
   QDFFRBS bottom_f_reg_1__0_ (.Q(bottom_f[3]),
	.D(bottom_1__0_),
	.CK(CTS_5),
	.RB(n1476));
   QDFFRBS bottom_f_reg_0__2_ (.Q(bottom_f[2]),
	.D(n763),
	.CK(CTS_5),
	.RB(n1476));
   QDFFRBS bottom_f_reg_0__1_ (.Q(bottom_f[1]),
	.D(n1468),
	.CK(CTS_5),
	.RB(n1476));
   QDFFRBS bottom_f_reg_0__0_ (.Q(bottom_f[0]),
	.D(bottom_0__0_),
	.CK(CTS_5),
	.RB(n1476));
   QDFFRBS map_f_reg_0__0_ (.Q(map_f_0__0_),
	.D(n660),
	.CK(CTS_6),
	.RB(n1476));
   QDFFRBS row_f_reg_0__0_ (.Q(row_f[0]),
	.D(N700),
	.CK(CTS_6),
	.RB(n1476));
   QDFFRBS bottom_compare_f_reg_2_ (.Q(bottom_compare_f[2]),
	.D(n7190),
	.CK(CTS_5),
	.RB(n1476));
   QDFFRBS bottom_compare_f_reg_3_ (.Q(N964),
	.D(n729),
	.CK(CTS_5),
	.RB(n1474));
   QDFFRBS map_f_reg_10__1_ (.Q(map_f_10__1_),
	.D(n649),
	.CK(CTS_2),
	.RB(n1475));
   QDFFRBS map_f_reg_9__1_ (.Q(map_f_9__1_),
	.D(n7030),
	.CK(CTS_2),
	.RB(n1476));
   QDFFRBS map_f_reg_8__1_ (.Q(map_f_8__1_),
	.D(n697),
	.CK(CTS_2),
	.RB(n1475));
   QDFFRBS map_f_reg_7__1_ (.Q(map_f_7__1_),
	.D(n727),
	.CK(CTS_3),
	.RB(n1476));
   QDFFRBS map_f_reg_6__1_ (.Q(map_f_6__1_),
	.D(n691),
	.CK(CTS_3),
	.RB(n1475));
   QDFFRBS map_f_reg_5__1_ (.Q(map_f_5__1_),
	.D(n685),
	.CK(CTS_3),
	.RB(n1474));
   QDFFRBS map_f_reg_4__1_ (.Q(map_f_4__1_),
	.D(n655),
	.CK(CTS_3),
	.RB(n1476));
   QDFFRBS map_f_reg_3__1_ (.Q(map_f_3__1_),
	.D(n679),
	.CK(CTS_6),
	.RB(n1476));
   QDFFRBS map_f_reg_2__1_ (.Q(map_f_2__1_),
	.D(n673),
	.CK(CTS_6),
	.RB(n1475));
   QDFFRBS map_f_reg_1__1_ (.Q(map_f_1__1_),
	.D(n667),
	.CK(CTS_6),
	.RB(n1474));
   QDFFRBS map_f_reg_0__1_ (.Q(map_f_0__1_),
	.D(n661),
	.CK(CTS_6),
	.RB(n1474));
   QDFFRBS row_f_reg_0__1_ (.Q(row_f[1]),
	.D(N701),
	.CK(CTS_6),
	.RB(n1479));
   QDFFRBS map_f_reg_12__1_ (.Q(map_f_12__1_),
	.D(n7150),
	.CK(CTS_6),
	.RB(n1479));
   QDFFRBS cnt_f_reg_0_ (.Q(cnt_f[0]),
	.D(cnt[0]),
	.CK(CTS_2),
	.RB(n1479));
   QDFFRBS cnt_f_reg_1_ (.Q(cnt_f[1]),
	.D(cnt[1]),
	.CK(CTS_2),
	.RB(n1479));
   QDFFRBS cnt_f_reg_2_ (.Q(cnt_f[2]),
	.D(cnt[2]),
	.CK(CTS_2),
	.RB(n1479));
   QDFFRBS cnt_f_reg_3_ (.Q(cnt_f[3]),
	.D(cnt[3]),
	.CK(CTS_2),
	.RB(n1479));
   QDFFRBS map_f_reg_12__0_ (.Q(map_f_12__0_),
	.D(n7140),
	.CK(CTS_6),
	.RB(n1479));
   QDFFRBS map_f_reg_11__0_ (.Q(map_f_11__0_),
	.D(n7080),
	.CK(CTS_5),
	.RB(n1479));
   QDFFRBS map_f_reg_10__5_ (.Q(map_f_10__5_),
	.D(n653),
	.CK(CTS_2),
	.RB(n1479));
   QDFFRBS map_f_reg_9__5_ (.Q(map_f_9__5_),
	.D(n7070),
	.CK(CTS_2),
	.RB(n1479));
   QDFFRBS map_f_reg_8__5_ (.Q(map_f_8__5_),
	.D(n7010),
	.CK(CTS_2),
	.RB(n1479));
   QDFFRBS map_f_reg_7__5_ (.Q(map_f_7__5_),
	.D(n7230),
	.CK(CTS_3),
	.RB(n1479));
   QDFFRBS map_f_reg_6__5_ (.Q(map_f_6__5_),
	.D(n695),
	.CK(CTS_3),
	.RB(n1479));
   QDFFRBS map_f_reg_5__5_ (.Q(map_f_5__5_),
	.D(n689),
	.CK(CTS_3),
	.RB(n1479));
   QDFFRBS map_f_reg_4__5_ (.Q(map_f_4__5_),
	.D(n659),
	.CK(CTS_3),
	.RB(n1479));
   QDFFRBS map_f_reg_3__5_ (.Q(map_f_3__5_),
	.D(n683),
	.CK(CTS_3),
	.RB(n1479));
   QDFFRBS map_f_reg_2__5_ (.Q(map_f_2__5_),
	.D(n677),
	.CK(CTS_3),
	.RB(n1479));
   QDFFRBS map_f_reg_1__5_ (.Q(map_f_1__5_),
	.D(n671),
	.CK(CTS_3),
	.RB(n1479));
   QDFFRBS map_f_reg_0__5_ (.Q(map_f_0__5_),
	.D(n665),
	.CK(CTS_6),
	.RB(n1479));
   QDFFRBS row_f_reg_0__5_ (.Q(row_f[5]),
	.D(N705),
	.CK(CTS_6),
	.RB(n1479));
   QDFFRBS map_f_reg_12__5_ (.Q(map_f_12__5_),
	.D(n7220),
	.CK(CTS_6),
	.RB(n1479));
   QDFFRBS map_f_reg_11__5_ (.Q(map_f_11__5_),
	.D(n7130),
	.CK(CTS_5),
	.RB(n1479));
   QDFFRBS row_f_reg_3__5_ (.Q(row_f[23]),
	.D(N723),
	.CK(CTS_6),
	.RB(n1479));
   QDFFRBS row_f_reg_2__5_ (.Q(row_f[17]),
	.D(N717),
	.CK(CTS_6),
	.RB(n1479));
   QDFFRBS row_f_reg_1__5_ (.Q(row_f[11]),
	.D(N711),
	.CK(CTS_6),
	.RB(n1479));
   QDFFRBS map_f_reg_10__4_ (.Q(map_f_10__4_),
	.D(n652),
	.CK(CTS_2),
	.RB(n1479));
   QDFFRBS map_f_reg_9__4_ (.Q(map_f_9__4_),
	.D(n7060),
	.CK(CTS_2),
	.RB(n1479));
   QDFFRBS map_f_reg_8__4_ (.Q(map_f_8__4_),
	.D(n7000),
	.CK(CTS_2),
	.RB(n1479));
   QDFFRBS map_f_reg_7__4_ (.Q(map_f_7__4_),
	.D(n724),
	.CK(CTS_3),
	.RB(n1479));
   QDFFRBS map_f_reg_6__4_ (.Q(map_f_6__4_),
	.D(n694),
	.CK(CTS_3),
	.RB(n1479));
   QDFFRBS map_f_reg_5__4_ (.Q(map_f_5__4_),
	.D(n688),
	.CK(CTS_3),
	.RB(n1479));
   QDFFRBS map_f_reg_4__4_ (.Q(map_f_4__4_),
	.D(n658),
	.CK(CTS_3),
	.RB(n1479));
   QDFFRBS map_f_reg_3__4_ (.Q(map_f_3__4_),
	.D(n682),
	.CK(CTS_3),
	.RB(n1474));
   QDFFRBS map_f_reg_2__4_ (.Q(map_f_2__4_),
	.D(n676),
	.CK(CTS_3),
	.RB(n1475));
   QDFFRBS map_f_reg_1__4_ (.Q(map_f_1__4_),
	.D(n670),
	.CK(CTS_3),
	.RB(n1476));
   QDFFRBS map_f_reg_0__4_ (.Q(map_f_0__4_),
	.D(n664),
	.CK(CTS_6),
	.RB(n1475));
   QDFFRBS row_f_reg_0__4_ (.Q(row_f[4]),
	.D(N704),
	.CK(CTS_6),
	.RB(n1476));
   QDFFRBS map_f_reg_12__4_ (.Q(map_f_12__4_),
	.D(n7180),
	.CK(CTS_5),
	.RB(n1474));
   QDFFRBS map_f_reg_11__4_ (.Q(map_f_11__4_),
	.D(n7120),
	.CK(CTS_5),
	.RB(n1476));
   QDFFRBS row_f_reg_3__4_ (.Q(row_f[22]),
	.D(N722),
	.CK(CTS_6),
	.RB(n1474));
   QDFFRBS row_f_reg_2__4_ (.Q(row_f[16]),
	.D(N716),
	.CK(CTS_6),
	.RB(n1476));
   QDFFRBS row_f_reg_1__4_ (.Q(row_f[10]),
	.D(N710),
	.CK(CTS_6),
	.RB(n1475));
   QDFFRBS map_f_reg_10__3_ (.Q(map_f_10__3_),
	.D(n651),
	.CK(CTS_2),
	.RB(n1475));
   QDFFRBS map_f_reg_9__3_ (.Q(map_f_9__3_),
	.D(n7050),
	.CK(CTS_2),
	.RB(n1474));
   QDFFRBS map_f_reg_8__3_ (.Q(map_f_8__3_),
	.D(n699),
	.CK(CTS_2),
	.RB(n1481));
   QDFFRBS map_f_reg_7__3_ (.Q(map_f_7__3_),
	.D(n725),
	.CK(CTS_3),
	.RB(n1481));
   QDFFRBS map_f_reg_6__3_ (.Q(map_f_6__3_),
	.D(n693),
	.CK(CTS_3),
	.RB(n1481));
   QDFFRBS map_f_reg_5__3_ (.Q(map_f_5__3_),
	.D(n687),
	.CK(CTS_3),
	.RB(n1481));
   QDFFRBS map_f_reg_4__3_ (.Q(map_f_4__3_),
	.D(n657),
	.CK(CTS_3),
	.RB(n1480));
   QDFFRBS map_f_reg_3__3_ (.Q(map_f_3__3_),
	.D(n681),
	.CK(CTS_3),
	.RB(n1481));
   QDFFRBS map_f_reg_2__3_ (.Q(map_f_2__3_),
	.D(n675),
	.CK(CTS_3),
	.RB(n1480));
   QDFFRBS map_f_reg_1__3_ (.Q(map_f_1__3_),
	.D(n669),
	.CK(CTS_3),
	.RB(rst_n));
   QDFFRBS map_f_reg_0__3_ (.Q(map_f_0__3_),
	.D(n663),
	.CK(CTS_6),
	.RB(rst_n));
   QDFFRBS row_f_reg_0__3_ (.Q(row_f[3]),
	.D(N703),
	.CK(CTS_6),
	.RB(n1476));
   QDFFRBS map_f_reg_12__3_ (.Q(map_f_12__3_),
	.D(n7170),
	.CK(CTS_5),
	.RB(n1475));
   QDFFRBS map_f_reg_11__3_ (.Q(map_f_11__3_),
	.D(n7110),
	.CK(CTS_5),
	.RB(n1476));
   QDFFRBS row_f_reg_3__3_ (.Q(row_f[21]),
	.D(N721),
	.CK(CTS_6),
	.RB(n1475));
   QDFFRBS row_f_reg_2__3_ (.Q(row_f[15]),
	.D(N715),
	.CK(CTS_6),
	.RB(n1476));
   QDFFRBS row_f_reg_1__3_ (.Q(row_f[9]),
	.D(N709),
	.CK(CTS_6),
	.RB(n1474));
   QDFFRBS map_f_reg_10__2_ (.Q(map_f_10__2_),
	.D(n650),
	.CK(CTS_2),
	.RB(n1474));
   QDFFRBS map_f_reg_9__2_ (.Q(map_f_9__2_),
	.D(n7040),
	.CK(CTS_2),
	.RB(n1475));
   QDFFRBS map_f_reg_8__2_ (.Q(map_f_8__2_),
	.D(n698),
	.CK(CTS_2),
	.RB(n1476));
   QDFFRBS map_f_reg_7__2_ (.Q(map_f_7__2_),
	.D(n726),
	.CK(CTS_3),
	.RB(n1474));
   QDFFRBS map_f_reg_6__2_ (.Q(map_f_6__2_),
	.D(n692),
	.CK(CTS_3),
	.RB(n1475));
   QDFFRBS map_f_reg_4__2_ (.Q(map_f_4__2_),
	.D(n656),
	.CK(CTS_3),
	.RB(rst_n));
   QDFFRBS map_f_reg_3__2_ (.Q(map_f_3__2_),
	.D(n680),
	.CK(CTS_6),
	.RB(n1480));
   QDFFRBS map_f_reg_2__2_ (.Q(map_f_2__2_),
	.D(n674),
	.CK(CTS_3),
	.RB(n1480));
   QDFFRBS map_f_reg_1__2_ (.Q(map_f_1__2_),
	.D(n668),
	.CK(CTS_6),
	.RB(n1480));
   QDFFRBS map_f_reg_0__2_ (.Q(map_f_0__2_),
	.D(n662),
	.CK(CTS_6),
	.RB(n1475));
   QDFFRBS row_f_reg_0__2_ (.Q(row_f[2]),
	.D(N702),
	.CK(CTS_5),
	.RB(n1474));
   QDFFRBS map_f_reg_12__2_ (.Q(map_f_12__2_),
	.D(n7160),
	.CK(CTS_6),
	.RB(n1474));
   QDFFRBS map_f_reg_11__2_ (.Q(map_f_11__2_),
	.D(n7100),
	.CK(CTS_5),
	.RB(n1476));
   QDFFRBS row_f_reg_3__2_ (.Q(row_f[20]),
	.D(N720),
	.CK(CTS_6),
	.RB(n1476));
   QDFFRBS row_f_reg_2__2_ (.Q(row_f[14]),
	.D(N714),
	.CK(CTS_6),
	.RB(n1474));
   QDFFRBS row_f_reg_1__2_ (.Q(row_f[8]),
	.D(N708),
	.CK(CTS_6),
	.RB(n1475));
   QDFFRBS map_f_reg_11__1_ (.Q(map_f_11__1_),
	.D(n7090),
	.CK(CTS_5),
	.RB(n1477));
   QDFFRBS row_f_reg_3__1_ (.Q(row_f[19]),
	.D(N719),
	.CK(CTS_6),
	.RB(n1477));
   QDFFRBS row_f_reg_2__1_ (.Q(row_f[13]),
	.D(N713),
	.CK(CTS_6),
	.RB(n1477));
   QDFFRBS row_f_reg_1__1_ (.Q(row_f[7]),
	.D(N707),
	.CK(CTS_6),
	.RB(n1477));
   QDFFRBS map_f_reg_10__0_ (.Q(map_f_10__0_),
	.D(n648),
	.CK(CTS_2),
	.RB(n1477));
   QDFFRBS map_f_reg_9__0_ (.Q(map_f_9__0_),
	.D(n7020),
	.CK(CTS_2),
	.RB(n1477));
   QDFFRBS map_f_reg_8__0_ (.Q(map_f_8__0_),
	.D(n696),
	.CK(CTS_2),
	.RB(n1477));
   QDFFRBS map_f_reg_7__0_ (.Q(map_f_7__0_),
	.D(n728),
	.CK(CTS_3),
	.RB(n1477));
   QDFFRBS map_f_reg_6__0_ (.Q(map_f_6__0_),
	.D(n690),
	.CK(CTS_3),
	.RB(n1477));
   QDFFRBS map_f_reg_4__0_ (.Q(map_f_4__0_),
	.D(n654),
	.CK(CTS_3),
	.RB(n1477));
   QDFFRBS map_f_reg_3__0_ (.Q(map_f_3__0_),
	.D(n678),
	.CK(CTS_6),
	.RB(n1477));
   QDFFRBS row_f_reg_3__0_ (.Q(row_f[18]),
	.D(N718),
	.CK(CTS_6),
	.RB(n1480));
   QDFFRBS map_f_reg_2__0_ (.Q(map_f_2__0_),
	.D(n672),
	.CK(CTS_6),
	.RB(n1480));
   QDFFRBS row_f_reg_2__0_ (.Q(row_f[12]),
	.D(N712),
	.CK(CTS_6),
	.RB(n1480));
   QDFFRBS map_f_reg_1__0_ (.Q(map_f_1__0_),
	.D(n666),
	.CK(CTS_6),
	.RB(n1480));
   QDFFRBS row_f_reg_1__0_ (.Q(row_f[6]),
	.D(N706),
	.CK(CTS_6),
	.RB(n1480));
   QDFFRBS score_f_reg_0_ (.Q(score_f[0]),
	.D(n647),
	.CK(CTS_3),
	.RB(n1480));
   QDFFRBS score_f_reg_1_ (.Q(score_f[1]),
	.D(n646),
	.CK(CTS_3),
	.RB(n1480));
   QDFFRBS score_f_reg_2_ (.Q(score_f[2]),
	.D(n645),
	.CK(CTS_3),
	.RB(n1480));
   QDFFRBS score_f_reg_3_ (.Q(score_f[3]),
	.D(n644),
	.CK(CTS_3),
	.RB(n1480));
   QDFFRBN fail_reg (.Q(fail),
	.D(n1471),
	.CK(CTS_3),
	.RB(n1480));
   QDFFRBN tetris_valid_reg (.Q(tetris_valid),
	.D(n1469),
	.CK(CTS_3),
	.RB(n1480));
   QDFFRBN score_reg_3_ (.Q(score[3]),
	.D(score_comb[3]),
	.CK(CTS_3),
	.RB(n1480));
   QDFFRBN score_reg_2_ (.Q(score[2]),
	.D(score_comb[2]),
	.CK(CTS_3),
	.RB(n1480));
   QDFFRBN score_reg_1_ (.Q(score[1]),
	.D(score_comb[1]),
	.CK(CTS_3),
	.RB(n1480));
   QDFFRBN score_reg_0_ (.Q(score[0]),
	.D(score_comb[0]),
	.CK(CTS_3),
	.RB(n1480));
   QDFFRBN score_valid_reg (.Q(score_valid),
	.D(n1470),
	.CK(CTS_3),
	.RB(n1480));
   QDFFRBN tetris_reg_71_ (.Q(tetris[71]),
	.D(tetris_comb[71]),
	.CK(CTS_5),
	.RB(n1480));
   QDFFRBN tetris_reg_70_ (.Q(tetris[70]),
	.D(tetris_comb[70]),
	.CK(CTS_5),
	.RB(n1480));
   QDFFRBN tetris_reg_69_ (.Q(tetris[69]),
	.D(tetris_comb[69]),
	.CK(CTS_5),
	.RB(n1480));
   QDFFRBN tetris_reg_68_ (.Q(tetris[68]),
	.D(tetris_comb[68]),
	.CK(CTS_5),
	.RB(n1480));
   QDFFRBN tetris_reg_67_ (.Q(tetris[67]),
	.D(tetris_comb[67]),
	.CK(CTS_5),
	.RB(n1480));
   QDFFRBN tetris_reg_66_ (.Q(tetris[66]),
	.D(tetris_comb[66]),
	.CK(CTS_5),
	.RB(n1480));
   QDFFRBN tetris_reg_65_ (.Q(tetris[65]),
	.D(tetris_comb[65]),
	.CK(CTS_5),
	.RB(n1480));
   QDFFRBN tetris_reg_64_ (.Q(tetris[64]),
	.D(tetris_comb[64]),
	.CK(CTS_5),
	.RB(n1480));
   QDFFRBN tetris_reg_63_ (.Q(tetris[63]),
	.D(tetris_comb[63]),
	.CK(CTS_5),
	.RB(n1480));
   QDFFRBN tetris_reg_62_ (.Q(tetris[62]),
	.D(tetris_comb[62]),
	.CK(CTS_5),
	.RB(n1480));
   QDFFRBN tetris_reg_61_ (.Q(tetris[61]),
	.D(tetris_comb[61]),
	.CK(CTS_5),
	.RB(n1480));
   QDFFRBN tetris_reg_60_ (.Q(tetris[60]),
	.D(tetris_comb[60]),
	.CK(CTS_2),
	.RB(n1480));
   QDFFRBN tetris_reg_59_ (.Q(tetris[59]),
	.D(tetris_comb[59]),
	.CK(CTS_2),
	.RB(n1480));
   QDFFRBN tetris_reg_58_ (.Q(tetris[58]),
	.D(tetris_comb[58]),
	.CK(CTS_2),
	.RB(n1480));
   QDFFRBN tetris_reg_57_ (.Q(tetris[57]),
	.D(tetris_comb[57]),
	.CK(CTS_2),
	.RB(n1480));
   QDFFRBN tetris_reg_56_ (.Q(tetris[56]),
	.D(tetris_comb[56]),
	.CK(CTS_2),
	.RB(n1480));
   QDFFRBN tetris_reg_55_ (.Q(tetris[55]),
	.D(tetris_comb[55]),
	.CK(CTS_2),
	.RB(n1478));
   QDFFRBN tetris_reg_54_ (.Q(tetris[54]),
	.D(tetris_comb[54]),
	.CK(CTS_2),
	.RB(n1478));
   QDFFRBN tetris_reg_53_ (.Q(tetris[53]),
	.D(tetris_comb[53]),
	.CK(CTS_2),
	.RB(n1478));
   QDFFRBN tetris_reg_52_ (.Q(tetris[52]),
	.D(tetris_comb[52]),
	.CK(CTS_2),
	.RB(n1478));
   QDFFRBN tetris_reg_51_ (.Q(tetris[51]),
	.D(tetris_comb[51]),
	.CK(CTS_2),
	.RB(n1478));
   QDFFRBN tetris_reg_50_ (.Q(tetris[50]),
	.D(tetris_comb[50]),
	.CK(CTS_2),
	.RB(n1478));
   QDFFRBN tetris_reg_49_ (.Q(tetris[49]),
	.D(tetris_comb[49]),
	.CK(CTS_3),
	.RB(n1478));
   QDFFRBN tetris_reg_48_ (.Q(tetris[48]),
	.D(tetris_comb[48]),
	.CK(CTS_3),
	.RB(n1478));
   QDFFRBN tetris_reg_47_ (.Q(tetris[47]),
	.D(tetris_comb[47]),
	.CK(CTS_3),
	.RB(n1478));
   QDFFRBN tetris_reg_46_ (.Q(tetris[46]),
	.D(tetris_comb[46]),
	.CK(CTS_3),
	.RB(n1478));
   QDFFRBN tetris_reg_45_ (.Q(tetris[45]),
	.D(tetris_comb[45]),
	.CK(CTS_3),
	.RB(n1478));
   QDFFRBN tetris_reg_44_ (.Q(tetris[44]),
	.D(tetris_comb[44]),
	.CK(CTS_3),
	.RB(n1478));
   QDFFRBN tetris_reg_43_ (.Q(tetris[43]),
	.D(tetris_comb[43]),
	.CK(CTS_3),
	.RB(n1481));
   QDFFRBN tetris_reg_42_ (.Q(tetris[42]),
	.D(tetris_comb[42]),
	.CK(CTS_3),
	.RB(n1481));
   QDFFRBN tetris_reg_41_ (.Q(tetris[41]),
	.D(tetris_comb[41]),
	.CK(CTS_3),
	.RB(n1481));
   QDFFRBN tetris_reg_40_ (.Q(tetris[40]),
	.D(tetris_comb[40]),
	.CK(CTS_3),
	.RB(n1481));
   QDFFRBN tetris_reg_39_ (.Q(tetris[39]),
	.D(tetris_comb[39]),
	.CK(CTS_3),
	.RB(n1481));
   QDFFRBN tetris_reg_38_ (.Q(tetris[38]),
	.D(tetris_comb[38]),
	.CK(CTS_3),
	.RB(n1481));
   QDFFRBN tetris_reg_37_ (.Q(tetris[37]),
	.D(tetris_comb[37]),
	.CK(CTS_3),
	.RB(n1481));
   QDFFRBN tetris_reg_36_ (.Q(tetris[36]),
	.D(tetris_comb[36]),
	.CK(CTS_3),
	.RB(n1481));
   QDFFRBN tetris_reg_35_ (.Q(tetris[35]),
	.D(tetris_comb[35]),
	.CK(CTS_3),
	.RB(n1481));
   QDFFRBN tetris_reg_34_ (.Q(tetris[34]),
	.D(tetris_comb[34]),
	.CK(CTS_3),
	.RB(n1481));
   QDFFRBN tetris_reg_33_ (.Q(tetris[33]),
	.D(tetris_comb[33]),
	.CK(CTS_2),
	.RB(n1481));
   QDFFRBN tetris_reg_32_ (.Q(tetris[32]),
	.D(tetris_comb[32]),
	.CK(CTS_2),
	.RB(n1481));
   QDFFRBN tetris_reg_31_ (.Q(tetris[31]),
	.D(tetris_comb[31]),
	.CK(CTS_2),
	.RB(n1481));
   QDFFRBN tetris_reg_30_ (.Q(tetris[30]),
	.D(tetris_comb[30]),
	.CK(CTS_2),
	.RB(n1481));
   QDFFRBN tetris_reg_29_ (.Q(tetris[29]),
	.D(tetris_comb[29]),
	.CK(CTS_2),
	.RB(n1481));
   QDFFRBN tetris_reg_28_ (.Q(tetris[28]),
	.D(tetris_comb[28]),
	.CK(CTS_2),
	.RB(n1481));
   QDFFRBN tetris_reg_27_ (.Q(tetris[27]),
	.D(tetris_comb[27]),
	.CK(CTS_6),
	.RB(n1481));
   QDFFRBN tetris_reg_26_ (.Q(tetris[26]),
	.D(tetris_comb[26]),
	.CK(CTS_6),
	.RB(n1481));
   QDFFRBN tetris_reg_25_ (.Q(tetris[25]),
	.D(tetris_comb[25]),
	.CK(CTS_6),
	.RB(n1481));
   QDFFRBN tetris_reg_24_ (.Q(tetris[24]),
	.D(tetris_comb[24]),
	.CK(CTS_6),
	.RB(n1481));
   QDFFRBN tetris_reg_23_ (.Q(tetris[23]),
	.D(tetris_comb[23]),
	.CK(CTS_6),
	.RB(n1481));
   QDFFRBN tetris_reg_22_ (.Q(tetris[22]),
	.D(tetris_comb[22]),
	.CK(CTS_6),
	.RB(n1481));
   QDFFRBN tetris_reg_21_ (.Q(tetris[21]),
	.D(tetris_comb[21]),
	.CK(CTS_6),
	.RB(n1481));
   QDFFRBN tetris_reg_20_ (.Q(tetris[20]),
	.D(tetris_comb[20]),
	.CK(CTS_6),
	.RB(n1481));
   QDFFRBN tetris_reg_19_ (.Q(tetris[19]),
	.D(tetris_comb[19]),
	.CK(CTS_6),
	.RB(n1481));
   QDFFRBN tetris_reg_18_ (.Q(tetris[18]),
	.D(tetris_comb[18]),
	.CK(CTS_6),
	.RB(n1481));
   QDFFRBN tetris_reg_17_ (.Q(tetris[17]),
	.D(tetris_comb[17]),
	.CK(CTS_6),
	.RB(n1481));
   QDFFRBN tetris_reg_16_ (.Q(tetris[16]),
	.D(tetris_comb[16]),
	.CK(CTS_3),
	.RB(n1481));
   QDFFRBN tetris_reg_15_ (.Q(tetris[15]),
	.D(tetris_comb[15]),
	.CK(CTS_3),
	.RB(n1481));
   QDFFRBN tetris_reg_14_ (.Q(tetris[14]),
	.D(tetris_comb[14]),
	.CK(CTS_3),
	.RB(n1481));
   QDFFRBN tetris_reg_13_ (.Q(tetris[13]),
	.D(tetris_comb[13]),
	.CK(CTS_6),
	.RB(n1481));
   QDFFRBN tetris_reg_12_ (.Q(tetris[12]),
	.D(tetris_comb[12]),
	.CK(CTS_6),
	.RB(n1481));
   QDFFRBN tetris_reg_11_ (.Q(tetris[11]),
	.D(tetris_comb[11]),
	.CK(CTS_6),
	.RB(n1479));
   QDFFRBN tetris_reg_10_ (.Q(tetris[10]),
	.D(tetris_comb[10]),
	.CK(CTS_6),
	.RB(n1479));
   QDFFRBN tetris_reg_9_ (.Q(tetris[9]),
	.D(tetris_comb[9]),
	.CK(CTS_6),
	.RB(n1479));
   QDFFRBN tetris_reg_8_ (.Q(tetris[8]),
	.D(tetris_comb[8]),
	.CK(CTS_6),
	.RB(n1479));
   QDFFRBN tetris_reg_7_ (.Q(tetris[7]),
	.D(tetris_comb[7]),
	.CK(CTS_6),
	.RB(n1479));
   QDFFRBN tetris_reg_6_ (.Q(tetris[6]),
	.D(tetris_comb[6]),
	.CK(CTS_6),
	.RB(n1479));
   QDFFRBN tetris_reg_5_ (.Q(tetris[5]),
	.D(tetris_comb[5]),
	.CK(CTS_6),
	.RB(n1479));
   QDFFRBN tetris_reg_4_ (.Q(tetris[4]),
	.D(tetris_comb[4]),
	.CK(CTS_6),
	.RB(n1476));
   QDFFRBN tetris_reg_3_ (.Q(tetris[3]),
	.D(tetris_comb[3]),
	.CK(CTS_6),
	.RB(n1474));
   QDFFRBN tetris_reg_2_ (.Q(tetris[2]),
	.D(tetris_comb[2]),
	.CK(CTS_6),
	.RB(n1475));
   QDFFRBN tetris_reg_1_ (.Q(tetris[1]),
	.D(tetris_comb[1]),
	.CK(CTS_6),
	.RB(n1476));
   QDFFRBN tetris_reg_0_ (.Q(tetris[0]),
	.D(tetris_comb[0]),
	.CK(CTS_6),
	.RB(rst_n));
   QDFFRBS col_top_f_reg_5__3_ (.Q(col_top_f[23]),
	.D(col_top[23]),
	.CK(CTS_2),
	.RB(n1476));
   QDFFRBS col_top_f_reg_5__2_ (.Q(col_top_f[22]),
	.D(col_top[22]),
	.CK(CTS_2),
	.RB(n1474));
   QDFFRBS col_top_f_reg_5__1_ (.Q(col_top_f[21]),
	.D(col_top[21]),
	.CK(CTS_2),
	.RB(n1475));
   QDFFRBS col_top_f_reg_5__0_ (.Q(col_top_f[20]),
	.D(col_top[20]),
	.CK(CTS_2),
	.RB(n1474));
   QDFFRBS col_top_f_reg_4__3_ (.Q(col_top_f[19]),
	.D(col_top[19]),
	.CK(CTS_2),
	.RB(n1476));
   QDFFRBS col_top_f_reg_4__2_ (.Q(col_top_f[18]),
	.D(col_top[18]),
	.CK(CTS_2),
	.RB(n1474));
   QDFFRBS col_top_f_reg_4__1_ (.Q(col_top_f[17]),
	.D(col_top[17]),
	.CK(CTS_2),
	.RB(n1475));
   QDFFRBS col_top_f_reg_4__0_ (.Q(col_top_f[16]),
	.D(col_top[16]),
	.CK(CTS_2),
	.RB(n1475));
   QDFFRBS col_top_f_reg_3__3_ (.Q(col_top_f[15]),
	.D(col_top[15]),
	.CK(CTS_2),
	.RB(n1476));
   QDFFRBS col_top_f_reg_3__2_ (.Q(col_top_f[14]),
	.D(col_top[14]),
	.CK(CTS_2),
	.RB(n1474));
   QDFFRBS col_top_f_reg_3__1_ (.Q(col_top_f[13]),
	.D(col_top[13]),
	.CK(CTS_2),
	.RB(n1475));
   QDFFRBS col_top_f_reg_3__0_ (.Q(col_top_f[12]),
	.D(col_top[12]),
	.CK(CTS_2),
	.RB(n1474));
   QDFFRBS col_top_f_reg_2__3_ (.Q(col_top_f[11]),
	.D(col_top[11]),
	.CK(CTS_2),
	.RB(n1476));
   QDFFRBS col_top_f_reg_2__2_ (.Q(col_top_f[10]),
	.D(col_top[10]),
	.CK(CTS_2),
	.RB(n1476));
   QDFFRBS col_top_f_reg_2__1_ (.Q(col_top_f[9]),
	.D(col_top[9]),
	.CK(CTS_2),
	.RB(n1474));
   QDFFRBS col_top_f_reg_2__0_ (.Q(col_top_f[8]),
	.D(col_top[8]),
	.CK(CTS_2),
	.RB(n1475));
   QDFFRBS col_top_f_reg_1__3_ (.Q(col_top_f[7]),
	.D(col_top[7]),
	.CK(CTS_2),
	.RB(n1476));
   QDFFRBS col_top_f_reg_1__2_ (.Q(col_top_f[6]),
	.D(col_top[6]),
	.CK(CTS_2),
	.RB(n1474));
   QDFFRBS col_top_f_reg_1__1_ (.Q(col_top_f[5]),
	.D(col_top[5]),
	.CK(CTS_2),
	.RB(n1476));
   QDFFRBS col_top_f_reg_1__0_ (.Q(col_top_f[4]),
	.D(col_top[4]),
	.CK(CTS_2),
	.RB(n1474));
   QDFFRBS col_top_f_reg_0__3_ (.Q(col_top_f[3]),
	.D(col_top[3]),
	.CK(CTS_2),
	.RB(n1475));
   QDFFRBS col_top_f_reg_0__2_ (.Q(col_top_f[2]),
	.D(col_top[2]),
	.CK(CTS_2),
	.RB(n1475));
   QDFFRBS col_top_f_reg_0__1_ (.Q(col_top_f[1]),
	.D(col_top[1]),
	.CK(CTS_2),
	.RB(n1474));
   QDFFRBS col_top_f_reg_0__0_ (.Q(col_top_f[0]),
	.D(col_top[0]),
	.CK(CTS_2),
	.RB(n1475));
   QDFFRBS position_f_reg_2_ (.Q(position_f[2]),
	.D(n643),
	.CK(CTS_5),
	.RB(n1474));
   QDFFRBS position_f_reg_1_ (.Q(position_f[1]),
	.D(n642),
	.CK(CTS_5),
	.RB(n1476));
   QDFFRBS position_f_reg_0_ (.Q(position_f[0]),
	.D(n641),
	.CK(CTS_5),
	.RB(n1475));
   FA1S intadd_3_U4 (.S(intadd_3_SUM_0_),
	.CO(intadd_3_n3),
	.A(intadd_3_B_0_),
	.B(bottom_f[1]),
	.CI(intadd_3_CI));
   FA1S intadd_3_U3 (.S(intadd_2_A_0_),
	.CO(intadd_3_n2),
	.A(intadd_3_B_1_),
	.B(intadd_3_A_1_),
	.CI(intadd_3_n3));
   FA1S intadd_3_U2 (.S(intadd_2_A_1_),
	.CO(intadd_3_n1),
	.A(intadd_3_B_2_),
	.B(intadd_3_A_2_),
	.CI(intadd_3_n2));
   QDFFRBS bottom_compare_f_reg_0_ (.Q(bottom_compare_f[0]),
	.D(n7210),
	.CK(CTS_5),
	.RB(n1476));
   QDFFRBS bottom_compare_f_reg_1_ (.Q(bottom_compare_f[1]),
	.D(n7200),
	.CK(CTS_5),
	.RB(n1476));
   QDFFRBN map_f_reg_5__2_ (.Q(map_f_5__2_),
	.D(n686),
	.CK(CTS_3),
	.RB(n1476));
   QDFFRBN map_f_reg_5__0_ (.Q(map_f_5__0_),
	.D(n684),
	.CK(CTS_3),
	.RB(n1477));
   DFFRBS state_reg_1_ (.Q(state[1]),
	.QB(n1482),
	.D(n1472),
	.CK(CTS_5),
	.RB(n1475));
   INV1S U915 (.O(n763),
	.I(in_valid));
   INV1S U916 (.O(n764),
	.I(n763));
   ND3S U917 (.O(n823),
	.I1(n780),
	.I2(n779),
	.I3(n778));
   OA112S U918 (.O(n825),
	.A1(n777),
	.B1(n776),
	.C1(n873),
	.C2(n792));
   ND3S U919 (.O(intadd_3_B_1_),
	.I1(n913),
	.I2(n912),
	.I3(n911));
   ND3S U920 (.O(n1161),
	.I1(n1163),
	.I2(n1425),
	.I3(n1328));
   ND3S U921 (.O(n988),
	.I1(n987),
	.I2(n986),
	.I3(n1013));
   ND3S U922 (.O(n1201),
	.I1(n951),
	.I2(n950),
	.I3(n949));
   ND3S U923 (.O(n1182),
	.I1(n939),
	.I2(n938),
	.I3(n937));
   ND3S U924 (.O(n1235),
	.I1(n1234),
	.I2(n1233),
	.I3(n1232));
   BUF1S U925 (.O(n1478),
	.I(n1481));
   BUF1 U926 (.O(n1477),
	.I(n1480));
   ND3S U927 (.O(n730),
	.I1(n890),
	.I2(n889),
	.I3(n888));
   ND3S U928 (.O(n744),
	.I1(n879),
	.I2(n878),
	.I3(n877));
   INV1S U929 (.O(n1246),
	.I(state[2]));
   ND2S U930 (.O(n765),
	.I1(state[0]),
	.I2(state[1]));
   NR2 U931 (.O(n1470),
	.I1(n1246),
	.I2(n765));
   ND2S U932 (.O(n1228),
	.I1(n1246),
	.I2(n765));
   INV1S U933 (.O(n1249),
	.I(n1470));
   ND2S U934 (.O(n1456),
	.I1(n1228),
	.I2(n1249));
   INV1S U935 (.O(n1473),
	.I(n1456));
   ND2S U936 (.O(n1054),
	.I1(n764),
	.I2(tetrominoes[1]));
   OR3S U937 (.O(n1465),
	.I1(n1054),
	.I2(tetrominoes[0]),
	.I3(tetrominoes[2]));
   INV1S U938 (.O(n1051),
	.I(tetrominoes[0]));
   ND2S U939 (.O(n1055),
	.I1(n1051),
	.I2(tetrominoes[2]));
   INV1S U940 (.O(n870),
	.I(n1055));
   INV1S U941 (.O(n1222),
	.I(tetrominoes[2]));
   ND2S U942 (.O(n1218),
	.I1(n1222),
	.I2(tetrominoes[0]));
   INV1S U943 (.O(n766),
	.I(n1218));
   NR2 U944 (.O(n917),
	.I1(n870),
	.I2(n766));
   INV1S U945 (.O(n1221),
	.I(tetrominoes[1]));
   NR2 U946 (.O(n1050),
	.I1(n917),
	.I2(n1221));
   INV1S U947 (.O(n1220),
	.I(n1050));
   ND2S U948 (.O(n767),
	.I1(n1221),
	.I2(n1055));
   ND3S U949 (.O(n1466),
	.I1(n764),
	.I2(n1220),
	.I3(n767));
   OAI12HS U950 (.O(n1467),
	.A1(n764),
	.B1(n1218),
	.B2(tetrominoes[1]));
   NR2 U951 (.O(n1468),
	.I1(n1218),
	.I2(n1054));
   NR2 U952 (.O(n769),
	.I1(map_f_12__0_),
	.I2(map_f_12__1_));
   NR3 U953 (.O(n768),
	.I1(map_f_12__5_),
	.I2(map_f_12__2_),
	.I3(map_f_12__3_));
   INV1S U954 (.O(n1293),
	.I(map_f_12__4_));
   AOI13HS U955 (.O(n1471),
	.A1(n1249),
	.B1(n769),
	.B2(n768),
	.B3(n1293));
   NR2 U956 (.O(n770),
	.I1(cnt_f[0]),
	.I2(cnt_f[3]));
   INV1S U957 (.O(n1212),
	.I(cnt_f[2]));
   INV1S U958 (.O(n1209),
	.I(cnt_f[1]));
   ND3S U959 (.O(n1247),
	.I1(n770),
	.I2(n1212),
	.I3(n1209));
   INV1S U960 (.O(n1210),
	.I(n1471));
   OAI12HS U961 (.O(n1469),
	.A1(n1210),
	.B1(n1247),
	.B2(n1249));
   MOAI1S U962 (.O(n1472),
	.A1(state[0]),
	.A2(n1482),
	.B1(state[0]),
	.B2(n1482));
   BUF2 U963 (.O(n1479),
	.I(rst_n));
   BUF2 U964 (.O(n1481),
	.I(rst_n));
   BUF2 U965 (.O(n1480),
	.I(rst_n));
   BUF2 U966 (.O(n1476),
	.I(rst_n));
   BUF2 U967 (.O(n1474),
	.I(rst_n));
   BUF2 U968 (.O(n1475),
	.I(rst_n));
   INV1S U969 (.O(n1462),
	.I(position_f[2]));
   ND3S U970 (.O(n873),
	.I1(position_f[1]),
	.I2(position_f[0]),
	.I3(n1462));
   INV1S U971 (.O(n1238),
	.I(n873));
   INV1S U972 (.O(n1464),
	.I(position_f[0]));
   INV1S U973 (.O(n1463),
	.I(position_f[1]));
   ND2S U974 (.O(n771),
	.I1(position_f[2]),
	.I2(n1463));
   NR2 U975 (.O(n1237),
	.I1(n1464),
	.I2(n771));
   AOI22S U976 (.O(n775),
	.A1(n1238),
	.A2(col_top_f[15]),
	.B1(n1237),
	.B2(col_top_f[23]));
   NR2 U977 (.O(n1240),
	.I1(position_f[0]),
	.I2(n771));
   ND2S U978 (.O(n772),
	.I1(position_f[1]),
	.I2(n1462));
   NR2 U979 (.O(n1239),
	.I1(position_f[0]),
	.I2(n772));
   AOI22S U980 (.O(n774),
	.A1(n1240),
	.A2(col_top_f[19]),
	.B1(n1239),
	.B2(col_top_f[11]));
   ND3S U981 (.O(n787),
	.I1(n1464),
	.I2(n1463),
	.I3(n1462));
   INV1S U982 (.O(n1257),
	.I(n787));
   ND3S U983 (.O(n874),
	.I1(n1463),
	.I2(n1462),
	.I3(position_f[0]));
   INV1S U984 (.O(n1256),
	.I(n874));
   AOI22S U985 (.O(n773),
	.A1(n1257),
	.A2(col_top_f[3]),
	.B1(n1256),
	.B2(col_top_f[7]));
   ND3S U986 (.O(intadd_3_B_2_),
	.I1(n775),
	.I2(n774),
	.I3(n773));
   ND2S U987 (.O(n1418),
	.I1(bottom_compare_f[1]),
	.I2(bottom_compare_f[0]));
   NR2 U988 (.O(n859),
	.I1(bottom_compare_f[2]),
	.I2(n1418));
   ND3S U989 (.O(n1275),
	.I1(state[0]),
	.I2(n1246),
	.I3(n1482));
   INV1S U990 (.O(n1267),
	.I(n1275));
   INV1S U991 (.O(n792),
	.I(col_top_f[16]));
   AOI22S U992 (.O(n777),
	.A1(n1239),
	.A2(col_top_f[12]),
	.B1(n1256),
	.B2(col_top_f[8]));
   AOI22S U993 (.O(n776),
	.A1(n1257),
	.A2(col_top_f[4]),
	.B1(col_top_f[20]),
	.B2(n1240));
   ND2S U994 (.O(n824),
	.I1(n825),
	.I2(bottom_f[3]));
   ND2S U995 (.O(n780),
	.I1(col_top_f[21]),
	.I2(n1240));
   AOI22S U996 (.O(n779),
	.A1(n1257),
	.A2(col_top_f[5]),
	.B1(n1238),
	.B2(col_top_f[17]));
   AOI22S U997 (.O(n778),
	.A1(n1239),
	.A2(col_top_f[13]),
	.B1(n1256),
	.B2(col_top_f[9]));
   NR2 U998 (.O(n840),
	.I1(n824),
	.I2(n823));
   INV1S U999 (.O(n884),
	.I(n1240));
   INV1S U1000 (.O(n797),
	.I(col_top_f[22]));
   AOI22S U1001 (.O(n782),
	.A1(n1239),
	.A2(col_top_f[14]),
	.B1(n1256),
	.B2(col_top_f[10]));
   AOI22S U1002 (.O(n781),
	.A1(n1257),
	.A2(col_top_f[6]),
	.B1(n1238),
	.B2(col_top_f[18]));
   OA112S U1003 (.O(n827),
	.A1(n782),
	.B1(n781),
	.C1(n884),
	.C2(n797));
   INV1S U1004 (.O(n786),
	.I(col_top_f[23]));
   AOI22S U1005 (.O(n784),
	.A1(n1239),
	.A2(col_top_f[15]),
	.B1(n1256),
	.B2(col_top_f[11]));
   AOI22S U1006 (.O(n783),
	.A1(n1257),
	.A2(col_top_f[7]),
	.B1(n1238),
	.B2(col_top_f[19]));
   OA112S U1007 (.O(n821),
	.A1(n784),
	.B1(n783),
	.C1(n884),
	.C2(n786));
   MOAI1S U1008 (.O(n785),
	.A1(bottom_f[2]),
	.A2(intadd_3_n1),
	.B1(bottom_f[2]),
	.B2(intadd_3_n1));
   MOAI1S U1009 (.O(n834),
	.A1(intadd_3_B_2_),
	.A2(n785),
	.B1(intadd_3_B_2_),
	.B2(n785));
   ND2S U1010 (.O(n855),
	.I1(n820),
	.I2(n834));
   INV1S U1011 (.O(n806),
	.I(bottom_f[9]));
   AO222S U1012 (.O(n805),
	.A1(n1257),
	.A2(col_top_f[14]),
	.B1(n1256),
	.B2(col_top_f[18]),
	.C1(n1239),
	.C2(col_top_f[22]));
   NR2 U1013 (.O(n801),
	.I1(n806),
	.I2(n805));
   INV1S U1014 (.O(n788),
	.I(col_top_f[15]));
   INV1S U1015 (.O(n1259),
	.I(n1239));
   INV1S U1016 (.O(n789),
	.I(col_top_f[19]));
   OA222S U1017 (.O(n800),
	.A1(n787),
	.A2(n788),
	.B1(n1259),
	.B2(n786),
	.C1(n874),
	.C2(n789));
   MOAI1S U1018 (.O(n791),
	.A1(n874),
	.A2(n788),
	.B1(n1257),
	.B2(col_top_f[11]));
   MOAI1S U1019 (.O(n790),
	.A1(n1259),
	.A2(n789),
	.B1(n1238),
	.B2(col_top_f[23]));
   NR2 U1020 (.O(n804),
	.I1(n791),
	.I2(n790));
   MOAI1S U1021 (.O(n794),
	.A1(n792),
	.A2(n1259),
	.B1(n1257),
	.B2(col_top_f[8]));
   INV1S U1022 (.O(n1260),
	.I(col_top_f[20]));
   MOAI1S U1023 (.O(n793),
	.A1(n1260),
	.A2(n873),
	.B1(col_top_f[12]),
	.B2(n1256));
   NR2 U1024 (.O(n811),
	.I1(n794),
	.I2(n793));
   ND2S U1025 (.O(n810),
	.I1(n811),
	.I2(bottom_f[6]));
   AOI22S U1026 (.O(n796),
	.A1(n1257),
	.A2(col_top_f[9]),
	.B1(n1256),
	.B2(col_top_f[13]));
   AOI22S U1027 (.O(n795),
	.A1(n1238),
	.A2(col_top_f[21]),
	.B1(n1239),
	.B2(col_top_f[17]));
   ND2S U1028 (.O(n808),
	.I1(n796),
	.I2(n795));
   NR2 U1029 (.O(n809),
	.I1(n810),
	.I2(n808));
   AO22S U1030 (.O(n799),
	.A1(n1257),
	.A2(col_top_f[10]),
	.B1(n1256),
	.B2(col_top_f[14]));
   MOAI1S U1031 (.O(n798),
	.A1(n873),
	.A2(n797),
	.B1(n1239),
	.B2(col_top_f[18]));
   NR2 U1032 (.O(n807),
	.I1(n799),
	.I2(n798));
   AN2S U1033 (.O(n854),
	.I1(n815),
	.I2(n817));
   FA1S U1034 (.S(n802),
	.CO(n815),
	.A(bottom_f[10]),
	.B(n801),
	.CI(n800));
   INV1S U1035 (.O(n819),
	.I(n802));
   FA1S U1036 (.S(n818),
	.CO(n817),
	.A(bottom_f[8]),
	.B(n804),
	.CI(n803));
   MOAI1S U1037 (.O(n837),
	.A1(n806),
	.A2(n805),
	.B1(n806),
	.B2(n805));
   FA1S U1038 (.S(n836),
	.CO(n803),
	.A(bottom_f[7]),
	.B(n809),
	.CI(n807));
   OAI22S U1039 (.O(n849),
	.A1(n810),
	.A2(n809),
	.B1(n808),
	.B2(n809));
   OA12S U1040 (.O(n1261),
	.A1(n810),
	.B1(n811),
	.B2(bottom_f[6]));
   AO222S U1041 (.O(n850),
	.A1(n1257),
	.A2(col_top_f[13]),
	.B1(n1256),
	.B2(col_top_f[17]),
	.C1(col_top_f[21]),
	.C2(n1239));
   FA1S U1042 (.CO(n812),
	.A(n849),
	.B(n1261),
	.CI(n850));
   FA1S U1043 (.CO(n813),
	.A(n837),
	.B(n836),
	.CI(n812));
   MAO222S U1044 (.O(n816),
	.A1(n819),
	.B1(n818),
	.C1(n813));
   ND2S U1045 (.O(n814),
	.I1(n817),
	.I2(n816));
   MOAI1S U1046 (.O(n1263),
	.A1(n817),
	.A2(n816),
	.B1(n815),
	.B2(n814));
   MOAI1S U1047 (.O(n864),
	.A1(n1263),
	.A2(n819),
	.B1(n1263),
	.B2(n818));
   INV1S U1048 (.O(n833),
	.I(n820));
   FA1S U1049 (.S(n835),
	.CO(n820),
	.A(bottom_f[5]),
	.B(n822),
	.CI(n821));
   INV1S U1050 (.O(n831),
	.I(n835));
   AN2S U1051 (.O(n839),
	.I1(n824),
	.I2(n823));
   NR3 U1052 (.O(n826),
	.I1(n840),
	.I2(intadd_3_SUM_0_),
	.I3(n839));
   OA12S U1053 (.O(n847),
	.A1(n824),
	.B1(n825),
	.B2(bottom_f[3]));
   MOAI1S U1054 (.O(n829),
	.A1(n826),
	.A2(n847),
	.B1(intadd_3_SUM_0_),
	.B2(n839));
   FA1S U1055 (.S(n838),
	.CO(n822),
	.A(bottom_f[4]),
	.B(n840),
	.CI(n827));
   INV1S U1056 (.O(n828),
	.I(n838));
   FA1S U1057 (.CO(n830),
	.A(n829),
	.B(intadd_2_A_0_),
	.CI(n828));
   FA1S U1058 (.CO(n832),
	.A(n831),
	.B(intadd_2_A_1_),
	.CI(n830));
   MAO222S U1059 (.O(n842),
	.A1(n834),
	.B1(n833),
	.C1(n832));
   INV1S U1060 (.O(n848),
	.I(n842));
   OAI22S U1061 (.O(n863),
	.A1(n842),
	.A2(intadd_2_A_1_),
	.B1(n848),
	.B2(n835));
   MOAI1S U1062 (.O(n857),
	.A1(n1263),
	.A2(n837),
	.B1(n1263),
	.B2(n836));
   OAI22S U1063 (.O(n856),
	.A1(n842),
	.A2(intadd_2_A_0_),
	.B1(n848),
	.B2(n838));
   OR2S U1064 (.O(n841),
	.I1(n840),
	.I2(n839));
   MOAI1S U1065 (.O(n1271),
	.A1(n842),
	.A2(intadd_3_SUM_0_),
	.B1(n842),
	.B2(n841));
   AOI22S U1066 (.O(n845),
	.A1(col_top_f[20]),
	.A2(n1237),
	.B1(n1238),
	.B2(col_top_f[12]));
   AOI22S U1067 (.O(n844),
	.A1(n1240),
	.A2(col_top_f[16]),
	.B1(n1239),
	.B2(col_top_f[8]));
   AOI22S U1068 (.O(n843),
	.A1(n1257),
	.A2(col_top_f[0]),
	.B1(col_top_f[4]),
	.B2(n1256));
   ND3S U1069 (.O(n1245),
	.I1(n845),
	.I2(n844),
	.I3(n843));
   INV1S U1070 (.O(n1244),
	.I(bottom_f[0]));
   MOAI1S U1071 (.O(n846),
	.A1(n1245),
	.A2(n1244),
	.B1(n1245),
	.B2(n1244));
   MOAI1S U1072 (.O(n1264),
	.A1(n848),
	.A2(n847),
	.B1(n848),
	.B2(n846));
   MOAI1S U1073 (.O(n1270),
	.A1(n1263),
	.A2(n850),
	.B1(n1263),
	.B2(n849));
   FA1S U1074 (.CO(n851),
	.A(n1271),
	.B(n1264),
	.CI(n1270));
   FA1S U1075 (.CO(n852),
	.A(n857),
	.B(n856),
	.CI(n851));
   FA1S U1076 (.CO(n853),
	.A(n864),
	.B(n863),
	.CI(n852));
   MAO222S U1077 (.O(n1269),
	.A1(n855),
	.B1(n854),
	.C1(n853));
   MOAI1S U1078 (.O(n858),
	.A1(n1269),
	.A2(n857),
	.B1(n1269),
	.B2(n856));
   AOI22S U1079 (.O(n862),
	.A1(n1473),
	.A2(n859),
	.B1(n1267),
	.B2(n858));
   OR2S U1080 (.O(n869),
	.I1(state[2]),
	.I2(state[0]));
   NR2 U1081 (.O(n1283),
	.I1(row_f[3]),
	.I2(tetrominoes_map_f[3]));
   NR2 U1082 (.O(n1282),
	.I1(row_f[4]),
	.I2(tetrominoes_map_f[4]));
   NR2 U1083 (.O(n1284),
	.I1(row_f[2]),
	.I2(tetrominoes_map_f[2]));
   NR2 U1084 (.O(n1255),
	.I1(row_f[5]),
	.I2(tetrominoes_map_f[5]));
   NR2 U1085 (.O(n860),
	.I1(n1284),
	.I2(n1255));
   OR2S U1086 (.O(n1286),
	.I1(row_f[1]),
	.I2(tetrominoes_map_f[1]));
   OR2S U1087 (.O(n1287),
	.I1(row_f[0]),
	.I2(tetrominoes_map_f[0]));
   ND3S U1088 (.O(n861),
	.I1(n860),
	.I2(n1286),
	.I3(n1287));
   NR3 U1089 (.O(n1453),
	.I1(n1283),
	.I2(n1282),
	.I3(n861));
   ND2S U1090 (.O(n1447),
	.I1(n1473),
	.I2(n1453));
   ND3S U1091 (.O(n1280),
	.I1(n1249),
	.I2(n869),
	.I3(n1447));
   AO12S U1092 (.O(n867),
	.A1(n1280),
	.B1(n1473),
	.B2(n1418));
   MOAI1S U1093 (.O(n7190),
	.A1(n862),
	.A2(n1280),
	.B1(bottom_compare_f[2]),
	.B2(n867));
   INV1S U1094 (.O(n1339),
	.I(N964));
   NR2 U1095 (.O(n1307),
	.I1(n1339),
	.I2(bottom_compare_f[2]));
   INV1S U1096 (.O(n1037),
	.I(n1307));
   INV1S U1097 (.O(n1424),
	.I(n1418));
   ND2S U1098 (.O(n959),
	.I1(n1339),
	.I2(bottom_compare_f[2]));
   INV1S U1099 (.O(n1396),
	.I(n959));
   ND2S U1100 (.O(n1252),
	.I1(n1424),
	.I2(n1396));
   ND2S U1101 (.O(n866),
	.I1(n1037),
	.I2(n1252));
   MOAI1S U1102 (.O(n865),
	.A1(n1269),
	.A2(n864),
	.B1(n1269),
	.B2(n863));
   AOI22S U1103 (.O(n868),
	.A1(n1473),
	.A2(n866),
	.B1(n1267),
	.B2(n865));
   MOAI1S U1104 (.O(n729),
	.A1(n868),
	.A2(n1280),
	.B1(N964),
	.B2(n867));
   ND2S U1105 (.O(n872),
	.I1(tetrominoes_map_f[12]),
	.I2(n1228));
   NR2 U1106 (.O(n1248),
	.I1(n869),
	.I2(state[1]));
   ND2S U1107 (.O(n1215),
	.I1(n1248),
	.I2(n764));
   INV1S U1108 (.O(n1224),
	.I(n1215));
   NR2 U1109 (.O(n883),
	.I1(n1482),
	.I2(n869));
   AO12 U1110 (.O(n1236),
	.A1(n1267),
	.B1(n1257),
	.B2(n883));
   AOI22S U1111 (.O(n871),
	.A1(n1224),
	.A2(n870),
	.B1(tetrominoes_map_f[6]),
	.B2(n1236));
   ND2S U1112 (.O(n1219),
	.I1(n1221),
	.I2(n1224));
   ND3S U1113 (.O(n741),
	.I1(n872),
	.I2(n871),
	.I3(n1219));
   INV2 U1114 (.O(n1176),
	.I(n883));
   NR2 U1115 (.O(n1230),
	.I1(n873),
	.I2(n1176));
   ND2S U1116 (.O(n879),
	.I1(tetrominoes_map_f[12]),
	.I2(n1230));
   NR2 U1117 (.O(n875),
	.I1(n874),
	.I2(n1176));
   BUF1 U1118 (.O(n1231),
	.I(n875));
   AOI22S U1119 (.O(n878),
	.A1(n1231),
	.A2(tetrominoes_map_f[14]),
	.B1(tetrominoes_map_f[15]),
	.B2(n1236));
   NR2 U1120 (.O(n876),
	.I1(n1259),
	.I2(n1176));
   BUF1 U1121 (.O(n1229),
	.I(n876));
   AOI22S U1122 (.O(n877),
	.A1(tetrominoes_map_f[13]),
	.A2(n1229),
	.B1(tetrominoes_map_f[21]),
	.B2(n1228));
   ND2S U1123 (.O(n882),
	.I1(tetrominoes_map_f[6]),
	.I2(n1230));
   AOI22S U1124 (.O(n881),
	.A1(n1231),
	.A2(tetrominoes_map_f[8]),
	.B1(tetrominoes_map_f[9]),
	.B2(n1236));
   AOI22S U1125 (.O(n880),
	.A1(tetrominoes_map_f[7]),
	.A2(n1229),
	.B1(tetrominoes_map_f[15]),
	.B2(n1228));
   ND3S U1126 (.O(n738),
	.I1(n882),
	.I2(n881),
	.I3(n880));
   AN2S U1127 (.O(n903),
	.I1(n1237),
	.I2(n883));
   ND2S U1128 (.O(n887),
	.I1(n903),
	.I2(tetrominoes_map_f[18]));
   NR2 U1129 (.O(n907),
	.I1(n884),
	.I2(n1176));
   AOI22S U1130 (.O(n886),
	.A1(n1229),
	.A2(tetrominoes_map_f[21]),
	.B1(tetrominoes_map_f[19]),
	.B2(n907));
   AOI22S U1131 (.O(n885),
	.A1(n1267),
	.A2(tetrominoes_map_f[23]),
	.B1(n1230),
	.B2(tetrominoes_map_f[20]));
   ND3S U1132 (.O(n748),
	.I1(n887),
	.I2(n886),
	.I3(n885));
   AOI22S U1133 (.O(n890),
	.A1(n1267),
	.A2(tetrominoes_map_f[5]),
	.B1(tetrominoes_map_f[11]),
	.B2(n1228));
   AOI22S U1134 (.O(n889),
	.A1(tetrominoes_map_f[2]),
	.A2(n1230),
	.B1(tetrominoes_map_f[0]),
	.B2(n903));
   AOI22S U1135 (.O(n888),
	.A1(tetrominoes_map_f[3]),
	.A2(n1229),
	.B1(tetrominoes_map_f[1]),
	.B2(n907));
   AOI22S U1136 (.O(n893),
	.A1(n1267),
	.A2(tetrominoes_map_f[4]),
	.B1(tetrominoes_map_f[10]),
	.B2(n1228));
   AOI22S U1137 (.O(n892),
	.A1(tetrominoes_map_f[1]),
	.A2(n1230),
	.B1(tetrominoes_map_f[0]),
	.B2(n907));
   AOI22S U1138 (.O(n891),
	.A1(tetrominoes_map_f[3]),
	.A2(n1231),
	.B1(tetrominoes_map_f[2]),
	.B2(n1229));
   ND3S U1139 (.O(n731),
	.I1(n893),
	.I2(n892),
	.I3(n891));
   AOI22S U1140 (.O(n896),
	.A1(tetrominoes_map_f[10]),
	.A2(n1267),
	.B1(tetrominoes_map_f[16]),
	.B2(n1228));
   AOI22S U1141 (.O(n895),
	.A1(n1230),
	.A2(tetrominoes_map_f[7]),
	.B1(n907),
	.B2(tetrominoes_map_f[6]));
   AOI22S U1142 (.O(n894),
	.A1(n1229),
	.A2(tetrominoes_map_f[8]),
	.B1(n1231),
	.B2(tetrominoes_map_f[9]));
   ND3S U1143 (.O(n737),
	.I1(n896),
	.I2(n895),
	.I3(n894));
   AOI22S U1144 (.O(n899),
	.A1(tetrominoes_map_f[11]),
	.A2(n1267),
	.B1(tetrominoes_map_f[17]),
	.B2(n1228));
   AOI22S U1145 (.O(n898),
	.A1(n1230),
	.A2(tetrominoes_map_f[8]),
	.B1(n903),
	.B2(tetrominoes_map_f[6]));
   AOI22S U1146 (.O(n897),
	.A1(n1229),
	.A2(tetrominoes_map_f[9]),
	.B1(n907),
	.B2(tetrominoes_map_f[7]));
   ND3S U1147 (.O(n736),
	.I1(n899),
	.I2(n898),
	.I3(n897));
   ND2S U1148 (.O(n902),
	.I1(n907),
	.I2(tetrominoes_map_f[18]));
   AOI22S U1149 (.O(n901),
	.A1(n1230),
	.A2(tetrominoes_map_f[19]),
	.B1(n1231),
	.B2(tetrominoes_map_f[21]));
   AOI22S U1150 (.O(n900),
	.A1(n1267),
	.A2(tetrominoes_map_f[22]),
	.B1(n1229),
	.B2(tetrominoes_map_f[20]));
   ND3S U1151 (.O(n749),
	.I1(n902),
	.I2(n901),
	.I3(n900));
   AOI22S U1152 (.O(n906),
	.A1(tetrominoes_map_f[17]),
	.A2(n1267),
	.B1(tetrominoes_map_f[23]),
	.B2(n1228));
   AOI22S U1153 (.O(n905),
	.A1(n1230),
	.A2(tetrominoes_map_f[14]),
	.B1(n903),
	.B2(tetrominoes_map_f[12]));
   AOI22S U1154 (.O(n904),
	.A1(n1229),
	.A2(tetrominoes_map_f[15]),
	.B1(n907),
	.B2(tetrominoes_map_f[13]));
   ND3S U1155 (.O(n742),
	.I1(n906),
	.I2(n905),
	.I3(n904));
   AOI22S U1156 (.O(n910),
	.A1(tetrominoes_map_f[16]),
	.A2(n1267),
	.B1(tetrominoes_map_f[22]),
	.B2(n1228));
   AOI22S U1157 (.O(n909),
	.A1(n1230),
	.A2(tetrominoes_map_f[13]),
	.B1(n907),
	.B2(tetrominoes_map_f[12]));
   AOI22S U1158 (.O(n908),
	.A1(n1229),
	.A2(tetrominoes_map_f[14]),
	.B1(n1231),
	.B2(tetrominoes_map_f[15]));
   ND3S U1159 (.O(n743),
	.I1(n910),
	.I2(n909),
	.I3(n908));
   AOI22S U1160 (.O(n913),
	.A1(n1238),
	.A2(col_top_f[14]),
	.B1(n1237),
	.B2(col_top_f[22]));
   AOI22S U1161 (.O(n912),
	.A1(n1240),
	.A2(col_top_f[18]),
	.B1(n1239),
	.B2(col_top_f[10]));
   AOI22S U1162 (.O(n911),
	.A1(n1257),
	.A2(col_top_f[2]),
	.B1(n1256),
	.B2(col_top_f[6]));
   ND2S U1163 (.O(n916),
	.I1(tetrominoes_map_f[6]),
	.I2(n1229));
   MOAI1S U1164 (.O(n1046),
	.A1(n1051),
	.A2(tetrominoes[1]),
	.B1(n1051),
	.B2(tetrominoes[1]));
   NR2 U1165 (.O(n1056),
	.I1(n1222),
	.I2(n1046));
   AOI22S U1166 (.O(n915),
	.A1(n1224),
	.A2(n1056),
	.B1(tetrominoes_map_f[8]),
	.B2(n1236));
   AOI22S U1167 (.O(n914),
	.A1(tetrominoes_map_f[7]),
	.A2(n1231),
	.B1(tetrominoes_map_f[14]),
	.B2(n1228));
   ND3S U1168 (.O(n739),
	.I1(n916),
	.I2(n915),
	.I3(n914));
   ND2S U1169 (.O(n920),
	.I1(tetrominoes_map_f[1]),
	.I2(n1236));
   AOI22S U1170 (.O(n919),
	.A1(n1231),
	.A2(tetrominoes_map_f[0]),
	.B1(tetrominoes_map_f[7]),
	.B2(n1228));
   OAI12HS U1171 (.O(n918),
	.A1(n1224),
	.B1(tetrominoes[1]),
	.B2(n917));
   ND3S U1172 (.O(n734),
	.I1(n920),
	.I2(n919),
	.I3(n918));
   AOI22S U1173 (.O(n922),
	.A1(n1231),
	.A2(tetrominoes_map_f[13]),
	.B1(tetrominoes_map_f[14]),
	.B2(n1236));
   AOI22S U1174 (.O(n921),
	.A1(tetrominoes_map_f[12]),
	.A2(n1229),
	.B1(tetrominoes_map_f[20]),
	.B2(n1228));
   ND2S U1175 (.O(n745),
	.I1(n922),
	.I2(n921));
   AOI22S U1176 (.O(n924),
	.A1(n1231),
	.A2(tetrominoes_map_f[20]),
	.B1(tetrominoes_map_f[21]),
	.B2(n1236));
   AOI22S U1177 (.O(n923),
	.A1(n1230),
	.A2(tetrominoes_map_f[18]),
	.B1(n1229),
	.B2(tetrominoes_map_f[19]));
   ND2S U1178 (.O(n750),
	.I1(n924),
	.I2(n923));
   INV1S U1179 (.O(n1416),
	.I(bottom_compare_f[0]));
   NR2 U1180 (.O(n1041),
	.I1(n1416),
	.I2(n1176));
   NR2 U1181 (.O(n1300),
	.I1(bottom_compare_f[1]),
	.I2(n1037));
   OA12S U1182 (.O(n1301),
	.A1(N964),
	.B1(bottom_compare_f[1]),
	.B2(bottom_compare_f[2]));
   AOI22S U1183 (.O(n927),
	.A1(map_f_11__3_),
	.A2(n1300),
	.B1(n1301),
	.B2(map_f_12__3_));
   NR2 U1184 (.O(n1337),
	.I1(bottom_compare_f[1]),
	.I2(n959));
   INV1S U1185 (.O(n1419),
	.I(bottom_compare_f[2]));
   ND2S U1186 (.O(n1397),
	.I1(n1339),
	.I2(n1419));
   NR2 U1187 (.O(n1370),
	.I1(n1397),
	.I2(bottom_compare_f[1]));
   AOI22S U1188 (.O(n926),
	.A1(map_f_7__3_),
	.A2(n1337),
	.B1(map_f_3__3_),
	.B2(n1370));
   INV1S U1189 (.O(n1276),
	.I(bottom_compare_f[1]));
   NR2 U1190 (.O(n1325),
	.I1(n1276),
	.I2(n959));
   NR2 U1191 (.O(n1355),
	.I1(n1276),
	.I2(n1397));
   AOI22S U1192 (.O(n925),
	.A1(map_f_9__3_),
	.A2(n1325),
	.B1(map_f_5__3_),
	.B2(n1355));
   ND3S U1193 (.O(n1186),
	.I1(n927),
	.I2(n926),
	.I3(n925));
   AOI22S U1194 (.O(n930),
	.A1(n1041),
	.A2(n1186),
	.B1(row_f[21]),
	.B2(n1176));
   ND2S U1195 (.O(n1309),
	.I1(n1276),
	.I2(n1416));
   NR2 U1196 (.O(n1039),
	.I1(n1309),
	.I2(n1176));
   INV1S U1197 (.O(n1432),
	.I(map_f_10__3_));
   INV1S U1198 (.O(n1356),
	.I(n1397));
   AOI22S U1199 (.O(n928),
	.A1(n1396),
	.A2(map_f_6__3_),
	.B1(map_f_2__3_),
	.B2(n1356));
   NR2 U1200 (.O(n1290),
	.I1(n1339),
	.I2(n1419));
   ND2S U1201 (.O(n1027),
	.I1(n1290),
	.I2(map_f_12__3_));
   OAI112HS U1202 (.O(n1026),
	.A1(n928),
	.B1(n1027),
	.C1(n1432),
	.C2(n1037));
   NR2 U1203 (.O(n1202),
	.I1(bottom_compare_f[0]),
	.I2(n1176));
   AN2S U1204 (.O(n1034),
	.I1(bottom_compare_f[1]),
	.I2(n1202));
   INV1S U1205 (.O(n1315),
	.I(map_f_8__3_));
   INV1S U1206 (.O(n1294),
	.I(map_f_12__3_));
   INV1S U1207 (.O(n1406),
	.I(map_f_4__3_));
   OAI222S U1208 (.O(n1185),
	.A1(n959),
	.A2(n1315),
	.B1(n1294),
	.B2(n1339),
	.C1(n1397),
	.C2(n1406));
   AOI22S U1209 (.O(n929),
	.A1(n1039),
	.A2(n1026),
	.B1(n1034),
	.B2(n1185));
   ND2S U1210 (.O(N715),
	.I1(n930),
	.I2(n929));
   AOI22S U1211 (.O(n933),
	.A1(map_f_11__2_),
	.A2(n1300),
	.B1(n1301),
	.B2(map_f_12__2_));
   AOI22S U1212 (.O(n932),
	.A1(map_f_7__2_),
	.A2(n1337),
	.B1(map_f_3__2_),
	.B2(n1370));
   AOI22S U1213 (.O(n931),
	.A1(map_f_9__2_),
	.A2(n1325),
	.B1(map_f_5__2_),
	.B2(n1355));
   ND3S U1214 (.O(n1190),
	.I1(n933),
	.I2(n932),
	.I3(n931));
   AOI22S U1215 (.O(n936),
	.A1(n1041),
	.A2(n1190),
	.B1(row_f[20]),
	.B2(n1176));
   INV1S U1216 (.O(n1435),
	.I(map_f_10__2_));
   AOI22S U1217 (.O(n934),
	.A1(n1396),
	.A2(map_f_6__2_),
	.B1(map_f_2__2_),
	.B2(n1356));
   ND2S U1218 (.O(n1035),
	.I1(n1290),
	.I2(map_f_12__2_));
   OAI112HS U1219 (.O(n1033),
	.A1(n934),
	.B1(n1035),
	.C1(n1435),
	.C2(n1037));
   INV1S U1220 (.O(n1317),
	.I(map_f_8__2_));
   INV1S U1221 (.O(n1295),
	.I(map_f_12__2_));
   INV1S U1222 (.O(n1408),
	.I(map_f_4__2_));
   OAI222S U1223 (.O(n1189),
	.A1(n959),
	.A2(n1317),
	.B1(n1295),
	.B2(n1339),
	.C1(n1397),
	.C2(n1408));
   AOI22S U1224 (.O(n935),
	.A1(n1039),
	.A2(n1033),
	.B1(n1034),
	.B2(n1189));
   ND2S U1225 (.O(N714),
	.I1(n936),
	.I2(n935));
   AOI22S U1226 (.O(n939),
	.A1(map_f_11__4_),
	.A2(n1300),
	.B1(n1301),
	.B2(map_f_12__4_));
   AOI22S U1227 (.O(n938),
	.A1(map_f_7__4_),
	.A2(n1337),
	.B1(map_f_3__4_),
	.B2(n1370));
   AOI22S U1228 (.O(n937),
	.A1(map_f_9__4_),
	.A2(n1325),
	.B1(map_f_5__4_),
	.B2(n1355));
   AOI22S U1229 (.O(n942),
	.A1(n1041),
	.A2(n1182),
	.B1(row_f[22]),
	.B2(n1176));
   INV1S U1230 (.O(n1429),
	.I(map_f_10__4_));
   AOI22S U1231 (.O(n940),
	.A1(n1396),
	.A2(map_f_6__4_),
	.B1(map_f_2__4_),
	.B2(n1356));
   ND2S U1232 (.O(n1020),
	.I1(n1290),
	.I2(map_f_12__4_));
   OAI112HS U1233 (.O(n1019),
	.A1(n940),
	.B1(n1020),
	.C1(n1429),
	.C2(n1037));
   INV1S U1234 (.O(n1313),
	.I(map_f_8__4_));
   INV1S U1235 (.O(n1404),
	.I(map_f_4__4_));
   OAI222S U1236 (.O(n1181),
	.A1(n959),
	.A2(n1313),
	.B1(n1293),
	.B2(n1339),
	.C1(n1397),
	.C2(n1404));
   AOI22S U1237 (.O(n941),
	.A1(n1039),
	.A2(n1019),
	.B1(n1034),
	.B2(n1181));
   ND2S U1238 (.O(N716),
	.I1(n942),
	.I2(n941));
   AOI22S U1239 (.O(n945),
	.A1(map_f_11__5_),
	.A2(n1300),
	.B1(n1301),
	.B2(map_f_12__5_));
   AOI22S U1240 (.O(n944),
	.A1(map_f_7__5_),
	.A2(n1337),
	.B1(map_f_3__5_),
	.B2(n1370));
   AOI22S U1241 (.O(n943),
	.A1(map_f_9__5_),
	.A2(n1325),
	.B1(map_f_5__5_),
	.B2(n1355));
   ND3S U1242 (.O(n1178),
	.I1(n945),
	.I2(n944),
	.I3(n943));
   AOI22S U1243 (.O(n948),
	.A1(n1041),
	.A2(n1178),
	.B1(row_f[23]),
	.B2(n1176));
   INV1S U1244 (.O(n1426),
	.I(map_f_10__5_));
   AOI22S U1245 (.O(n946),
	.A1(n1396),
	.A2(map_f_6__5_),
	.B1(map_f_2__5_),
	.B2(n1356));
   ND2S U1246 (.O(n1006),
	.I1(n1290),
	.I2(map_f_12__5_));
   OAI112HS U1247 (.O(n1005),
	.A1(n946),
	.B1(n1006),
	.C1(n1426),
	.C2(n1037));
   INV1S U1248 (.O(n1311),
	.I(map_f_8__5_));
   INV1S U1249 (.O(n1292),
	.I(map_f_12__5_));
   INV1S U1250 (.O(n1402),
	.I(map_f_4__5_));
   OAI222S U1251 (.O(n1177),
	.A1(n959),
	.A2(n1311),
	.B1(n1292),
	.B2(n1339),
	.C1(n1397),
	.C2(n1402));
   AOI22S U1252 (.O(n947),
	.A1(n1039),
	.A2(n1005),
	.B1(n1034),
	.B2(n1177));
   ND2S U1253 (.O(N717),
	.I1(n948),
	.I2(n947));
   AOI22S U1254 (.O(n951),
	.A1(map_f_11__0_),
	.A2(n1300),
	.B1(n1301),
	.B2(map_f_12__0_));
   AOI22S U1255 (.O(n950),
	.A1(map_f_7__0_),
	.A2(n1337),
	.B1(map_f_3__0_),
	.B2(n1370));
   AOI22S U1256 (.O(n949),
	.A1(map_f_9__0_),
	.A2(n1325),
	.B1(map_f_5__0_),
	.B2(n1355));
   AOI22S U1257 (.O(n954),
	.A1(n1041),
	.A2(n1201),
	.B1(row_f[18]),
	.B2(n1176));
   INV1S U1258 (.O(n1443),
	.I(map_f_10__0_));
   AOI22S U1259 (.O(n952),
	.A1(n1396),
	.A2(map_f_6__0_),
	.B1(map_f_2__0_),
	.B2(n1356));
   ND2S U1260 (.O(n1013),
	.I1(n1290),
	.I2(map_f_12__0_));
   OAI112HS U1261 (.O(n1012),
	.A1(n952),
	.B1(n1013),
	.C1(n1443),
	.C2(n1037));
   INV1S U1262 (.O(n1323),
	.I(map_f_8__0_));
   INV1S U1263 (.O(n1299),
	.I(map_f_12__0_));
   INV1S U1264 (.O(n1414),
	.I(map_f_4__0_));
   OAI222S U1265 (.O(n1199),
	.A1(n959),
	.A2(n1323),
	.B1(n1299),
	.B2(n1339),
	.C1(n1397),
	.C2(n1414));
   AOI22S U1266 (.O(n953),
	.A1(n1039),
	.A2(n1012),
	.B1(n1034),
	.B2(n1199));
   ND2S U1267 (.O(N712),
	.I1(n954),
	.I2(n953));
   AOI22S U1268 (.O(n957),
	.A1(map_f_11__1_),
	.A2(n1300),
	.B1(n1301),
	.B2(map_f_12__1_));
   AOI22S U1269 (.O(n956),
	.A1(map_f_7__1_),
	.A2(n1337),
	.B1(map_f_3__1_),
	.B2(n1370));
   AOI22S U1270 (.O(n955),
	.A1(map_f_9__1_),
	.A2(n1325),
	.B1(map_f_5__1_),
	.B2(n1355));
   ND3S U1271 (.O(n1194),
	.I1(n957),
	.I2(n956),
	.I3(n955));
   AOI22S U1272 (.O(n961),
	.A1(n1041),
	.A2(n1194),
	.B1(row_f[19]),
	.B2(n1176));
   INV1S U1273 (.O(n1438),
	.I(map_f_10__1_));
   AOI22S U1274 (.O(n958),
	.A1(n1396),
	.A2(map_f_6__1_),
	.B1(map_f_2__1_),
	.B2(n1356));
   ND2S U1275 (.O(n999),
	.I1(n1290),
	.I2(map_f_12__1_));
   OAI112HS U1276 (.O(n998),
	.A1(n958),
	.B1(n999),
	.C1(n1438),
	.C2(n1037));
   INV1S U1277 (.O(n1319),
	.I(map_f_8__1_));
   INV1S U1278 (.O(n1296),
	.I(map_f_12__1_));
   INV1S U1279 (.O(n1410),
	.I(map_f_4__1_));
   OAI222S U1280 (.O(n1193),
	.A1(n959),
	.A2(n1319),
	.B1(n1296),
	.B2(n1339),
	.C1(n1397),
	.C2(n1410));
   AOI22S U1281 (.O(n960),
	.A1(n1039),
	.A2(n998),
	.B1(n1034),
	.B2(n1193));
   ND2S U1282 (.O(N713),
	.I1(n961),
	.I2(n960));
   INV1S U1283 (.O(n1384),
	.I(map_f_1__4_));
   INV1S U1284 (.O(n1380),
	.I(n137